import { writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

// Intl.supportedValuesOf omits the bare "UTC" identifier, but it is our default and what pg-boss expects.
const zones = ["UTC", ...Intl.supportedValuesOf("timeZone").filter(zone => zone !== "UTC")]

const content = [
    "// Auto-generated by scripts/generate-timezones.ts — do not edit manually.",
    '// Committed snapshot of Intl.supportedValuesOf("timeZone") so codegen output and backend validation stay deterministic.',
    'import { z } from "zod"',
    "",
    "export const TIMEZONES = [",
    zones.map(zone => `    "${zone}"`).join(",\n"),
    "] as const",
    "",
    "export const timezoneSchema = z.enum(TIMEZONES)",
    "",
    "export type Timezone = z.infer<typeof timezoneSchema>",
    ""
].join("\n")

writeFileSync(join(dirname(fileURLToPath(import.meta.url)), "..", "Timezones.ts"), content)
