"""Shared generator backend for `terse generate` and `terse init`."""

from __future__ import annotations

import re
from collections.abc import Callable
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, TypeVar, cast
from urllib.parse import quote

from ._http import request_json
from ._project import assert_project_root, read_api_key


class MissingApiKeyError(RuntimeError):
    """Raised when `TERSE_API_KEY` is missing for a command that requires it."""


@dataclass(frozen=True)
class AttioObjectData:
    api_slug: str
    singular_noun: str


@dataclass(frozen=True)
class AttioInstanceData:
    id: str
    display_name: str
    objects: list[AttioObjectData] = field(default_factory=list)


@dataclass(frozen=True)
class SnowflakeInstanceData:
    id: str
    display_name: str


@dataclass(frozen=True)
class ToolDefinition:
    name: str
    display_name: str
    description: str
    integration: str
    is_read_only: bool
    parameters: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class CodegenInput:
    attio: list[AttioInstanceData] = field(default_factory=list)
    snowflake: list[SnowflakeInstanceData] = field(default_factory=list)
    tools: list[ToolDefinition] = field(default_factory=list)


@dataclass(frozen=True)
class GenerateResult:
    project_dir: Path
    output_path: Path
    summary_lines: list[str]


T = TypeVar("T")
_SUPPORTED_TOOL_SPECS: tuple[tuple[str, str, str], ...] = (
    ("attio", "attio_list_objects", "list_objects"),
    ("attio", "attio_query_records", "query_records"),
    ("attio", "attio_upsert_record", "upsert_record"),
    ("snowflake", "snowflakeExecuteQuery", "execute_query"),
    ("snowflake", "snowflakeExplainQuery", "explain_query"),
)
_SUPPORTED_TOOL_NAMES = {tool_name for _, tool_name, _ in _SUPPORTED_TOOL_SPECS}
_TOOL_METHOD_NAME_BY_TOOL = {tool_name: method_name for _, tool_name, method_name in _SUPPORTED_TOOL_SPECS}
_TOOL_NAME_ALIASES = {
    "snowflake_execute_query": "snowflakeExecuteQuery",
    "snowflake_explain_query": "snowflakeExplainQuery",
}
_TOOL_OUTPUT_MODEL_BY_TOOL = {
    "attio_list_objects": "AttioListObjectsToolOutput",
    "attio_query_records": "AttioQueryRecordsToolOutput",
    "attio_upsert_record": "AttioUpsertRecordToolOutput",
    "snowflakeExecuteQuery": "SnowflakeExecuteQueryToolOutput",
    "snowflakeExplainQuery": "SnowflakeExplainQueryToolOutput",
}


def generate_project(project_dir: Path | None = None) -> GenerateResult:
    """Generate Python helper bindings for the project's active integrations."""

    resolved_dir = assert_project_root(project_dir)
    api_key = read_api_key(resolved_dir)
    if not api_key:
        raise MissingApiKeyError(
            "Missing TERSE_API_KEY in .env.\nCreate a project with `terse init` or add TERSE_API_KEY to your .env file."
        )

    active_types = request_json("/integrations/active", api_key)
    active_set = {str(item).lower() for item in active_types} if isinstance(active_types, list) else set()

    codegen_input = _build_codegen_input(active_set, api_key)
    output_path = write_generated_module(resolved_dir, render_generated_module(codegen_input))

    return GenerateResult(
        project_dir=resolved_dir,
        output_path=output_path,
        summary_lines=_build_summary_lines(codegen_input),
    )


def render_generated_module(codegen_input: CodegenInput | None = None) -> str:
    """Render the generated Python helper module."""

    input_data = codegen_input or CodegenInput()
    exported_names = [
        "Schedule",
        "GeneratedTools",
        "create_tools",
        "attach_tools",
        "TerseAgent",
    ]
    attio_tools = _select_supported_tools(input_data.tools, "attio")
    snowflake_tools = _select_supported_tools(input_data.tools, "snowflake")
    tool_output_models = _selected_tool_output_models(attio_tools + snowflake_tools)
    exported_names.extend(tool_output_models)
    lines = [
        '"""Generated by `terse generate`. Do not edit manually."""',
        "",
        "from __future__ import annotations",
    ]

    if input_data.attio:
        lines.extend(
            [
                "",
                "from dataclasses import dataclass",
                "from types import SimpleNamespace",
            ]
        )
    if attio_tools:
        lines.extend(["", "import json"])
    if tool_output_models:
        lines.extend(
            [
                "",
                "from terse_sdk import (",
                *[f"    {model_name}," for model_name in tool_output_models],
                ")",
            ]
        )

    lines.extend(
        [
            "",
            "from terse_sdk import SkillConfig, TerseAgent as _SdkTerseAgent, TriggerConfig",
            "",
            "",
            "def _compact_dict(**values: object) -> dict[str, object]:",
            '    """Drop None values while preserving falsey config values like False and []."""',
            "",
            "    return {key: value for key, value in values.items() if value is not None}",
        ]
    )

    sections: list[list[str]] = []

    attio_section = _generate_attio_section(input_data.attio)
    if attio_section:
        sections.append(attio_section)
        exported_names.extend(["AttioObjectResource", "AttioObject", "Attio"])

    snowflake_section = _generate_snowflake_section(input_data.snowflake)
    if snowflake_section:
        sections.append(snowflake_section)
        exported_names.append("Snowflake")

    sections.append(_generate_schedule_section())
    sections.append(_generate_tools_section(input_data, attio_tools, snowflake_tools))

    for section in sections:
        lines.extend(["", "", *section])

    lines.extend(["", "", f"__all__ = {exported_names!r}", ""])
    return "\n".join(lines)


def write_generated_module(project_dir: Path, content: str) -> Path:
    """Write the generated helper module into the project's src directory."""

    output_path = project_dir / "src" / "terse_generated.py"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")
    return output_path


def _build_codegen_input(active_set: set[str], api_key: str) -> CodegenInput:
    return CodegenInput(
        attio=(_safe_fetch(lambda: _fetch_attio_instances(api_key)) if "attio" in active_set else []),
        snowflake=(_safe_fetch(lambda: _fetch_snowflake_instances(api_key)) if "snowflake" in active_set else []),
        tools=_safe_fetch(lambda: _fetch_tool_definitions(api_key, active_set)),
    )


def _safe_fetch(fetcher: Callable[[], list[T]]) -> list[T]:
    try:
        return fetcher()
    except Exception:
        return []


def _as_dict(value: object) -> dict[str, Any] | None:
    if isinstance(value, dict):
        return cast(dict[str, Any], value)
    return None


def _as_list(value: object) -> list[Any]:
    if isinstance(value, list):
        return cast(list[Any], value)
    return []


def _fetch_attio_instances(api_key: str) -> list[AttioInstanceData]:
    raw_instances = _as_list(request_json("/attio/integrations", api_key))
    instances: list[AttioInstanceData] = []

    for integration in raw_instances:
        integration_data = _as_dict(integration)
        if integration_data is None:
            continue

        integration_id = str(integration_data.get("id", ""))
        raw_objects = _safe_request_json(
            f"/attio/integrations/{quote(integration_id, safe='')}/objects",
            api_key,
        )
        objects = [
            AttioObjectData(
                api_slug=str((_as_dict(raw_object) or {}).get("api_slug", "")),
                singular_noun=str((_as_dict(raw_object) or {}).get("singular_noun", "")),
            )
            for raw_object in _as_list(raw_objects)
            if _as_dict(raw_object) is not None and str((_as_dict(raw_object) or {}).get("api_slug", ""))
        ]
        instances.append(
            AttioInstanceData(
                id=integration_id,
                display_name=str(integration_data.get("workspaceName") or integration_id),
                objects=objects,
            )
        )

    return instances


def _fetch_snowflake_instances(api_key: str) -> list[SnowflakeInstanceData]:
    raw_instances = _as_list(request_json("/snowflake/integrations", api_key))
    return [
        SnowflakeInstanceData(
            id=str((_as_dict(integration) or {}).get("id", "")),
            display_name=str(
                (_as_dict(integration) or {}).get("accountIdentifier") or (_as_dict(integration) or {}).get("id") or ""
            ),
        )
        for integration in raw_instances
        if _as_dict(integration) is not None
    ]


def _fetch_tool_definitions(api_key: str, active_set: set[str]) -> list[ToolDefinition]:
    raw_payload = _as_dict(request_json("/sdk/tool-definitions", api_key))
    raw_tools = _as_list(raw_payload.get("tools") if raw_payload is not None else None)
    definitions: list[ToolDefinition] = []

    for raw_tool in raw_tools:
        tool_data = _as_dict(raw_tool)
        if tool_data is None:
            continue

        integration = str(tool_data.get("integration", "")).lower()
        tool_name = _canonical_tool_name(str(tool_data.get("name", "")))
        if integration not in active_set or tool_name not in _SUPPORTED_TOOL_NAMES:
            continue

        definitions.append(
            ToolDefinition(
                name=tool_name,
                display_name=str(tool_data.get("displayName") or tool_name),
                description=str(tool_data.get("description") or ""),
                integration=integration,
                is_read_only=bool(tool_data.get("isReadOnly")),
                parameters=_as_dict(tool_data.get("parameters")) or {},
            )
        )

    return definitions


def _safe_request_json(path: str, api_key: str) -> object | None:
    try:
        return request_json(path, api_key)
    except Exception:
        return None


def _build_summary_lines(codegen_input: CodegenInput) -> list[str]:
    lines = [f"Attio ({instance.display_name}) — {len(instance.objects)} objects" for instance in codegen_input.attio]
    lines.extend(f"Snowflake ({instance.display_name})" for instance in codegen_input.snowflake)
    lines.append("Schedule trigger")
    return lines


def _generate_attio_section(instances: list[AttioInstanceData]) -> list[str]:
    if not instances:
        return []

    instance = instances[0]
    namespace_lines = _generate_attio_namespace(instance.objects)

    return [
        "# === Attio ===",
        "",
        *namespace_lines,
        "",
        "class Attio:",
        "    @staticmethod",
        "    def skill(*, obj: AttioObjectResource | None = None) -> SkillConfig:",
        (
            "        return SkillConfig("
            f"integration_id={instance.id!r}, "
            "integration_type='attio', "
            "config_type='attio_output', "
            "config=_compact_dict(objectSlug=obj.api_slug if obj else None)"
            ")"
        ),
    ]


def _generate_attio_namespace(objects: list[AttioObjectData]) -> list[str]:
    lines = [
        "@dataclass(frozen=True)",
        "class AttioObjectResource:",
        "    api_slug: str",
        "    name: str",
        "",
    ]

    if not objects:
        lines.append("AttioObject = SimpleNamespace()")
        return lines

    lines.append("AttioObject = SimpleNamespace(")
    used_names: set[str] = set()
    for obj in objects:
        static_name = _unique_name(_to_pascal_case(obj.singular_noun or obj.api_slug) or "Object", used_names)
        lines.append(f"    {static_name}=AttioObjectResource(api_slug={obj.api_slug!r}, name={obj.singular_noun!r}),")
    lines.append(")")
    return lines


def _generate_snowflake_section(instances: list[SnowflakeInstanceData]) -> list[str]:
    if not instances:
        return []

    instance = instances[0]
    return [
        "# === Snowflake ===",
        "",
        "class Snowflake:",
        "    @staticmethod",
        "    def skill(",
        "        *,",
        "        warehouse: str | None = None,",
        "        database_name: str | None = None,",
        "        schema_name: str | None = None,",
        "    ) -> SkillConfig:",
        (
            "        return SkillConfig("
            f"integration_id={instance.id!r}, "
            "integration_type='snowflake', "
            "config_type='snowflake_output', "
            "config=_compact_dict("
            "warehouse=warehouse, "
            "databaseName=database_name, "
            "schemaName=schema_name"
            ")"
            ")"
        ),
    ]


def _generate_schedule_section() -> list[str]:
    return [
        "# === Schedule ===",
        "",
        "class Schedule:",
        "    @staticmethod",
        "    def cron(expression: str) -> TriggerConfig:",
        (
            "        return TriggerConfig("
            "integration_id='system', "
            "integration_type='cron_job', "
            "config_type='time_trigger', "
            "config=_compact_dict(cronExpression=expression)"
            ")"
        ),
    ]


def _generate_tools_section(
    codegen_input: CodegenInput,
    attio_tools: list[ToolDefinition],
    snowflake_tools: list[ToolDefinition],
) -> list[str]:
    lines = ["# === Deterministic tools ===", ""]

    if attio_tools:
        lines.extend(_generate_tool_json_helpers())
        lines.extend(["", ""])

    if codegen_input.attio and attio_tools:
        lines.extend(_generate_attio_tools_class(codegen_input.attio[0], attio_tools))
        lines.extend(["", ""])

    if codegen_input.snowflake and snowflake_tools:
        lines.extend(_generate_snowflake_tools_class(codegen_input.snowflake[0], snowflake_tools))
        lines.extend(["", ""])

    lines.extend(
        _generate_generated_tools_class(
            has_attio_tools=bool(codegen_input.attio and attio_tools),
            has_snowflake_tools=bool(codegen_input.snowflake and snowflake_tools),
        )
    )
    lines.extend(["", ""])
    lines.extend(
        _generate_create_tools_functions(
            has_attio_tools=bool(codegen_input.attio and attio_tools),
            has_snowflake_tools=bool(codegen_input.snowflake and snowflake_tools),
        )
    )
    return lines


def _generate_tool_json_helpers() -> list[str]:
    return [
        "def _json_string(value: object | None) -> str | None:",
        "    if value is None:",
        "        return None",
        "    if isinstance(value, str):",
        "        return value",
        "    return json.dumps(value, separators=(',', ':'), sort_keys=True)",
    ]


def _generate_attio_tools_class(instance: AttioInstanceData, tools: list[ToolDefinition]) -> list[str]:
    lines = [
        "class _AttioTools:",
        "    def __init__(self, agent: _SdkTerseAgent) -> None:",
        "        self._agent = agent",
    ]

    for tool in tools:
        lines.extend([""])
        if tool.name == "attio_list_objects":
            lines.extend(
                [
                    f"    def list_objects(self) -> {_TOOL_OUTPUT_MODEL_BY_TOOL[tool.name]}:",
                    "        return AttioListObjectsToolOutput.model_validate(",
                    f"            self._agent.execute_tool({tool.name!r}, {{'integrationId': {instance.id!r}}})",
                    "        )",
                ]
            )
        elif tool.name == "attio_query_records":
            lines.extend(
                [
                    "    def query_records(",
                    "        self,",
                    "        *,",
                    "        obj: AttioObjectResource,",
                    "        filter: object | None = None,",
                    "        limit: int | None = None,",
                    f"    ) -> {_TOOL_OUTPUT_MODEL_BY_TOOL[tool.name]}:",
                    "        return AttioQueryRecordsToolOutput.model_validate(",
                    "            self._agent.execute_tool(",
                    f"                {tool.name!r},",
                    "                _compact_dict(",
                    f"                    integrationId={instance.id!r},",
                    "                    objectSlug=obj.api_slug,",
                    "                    filter=_json_string(filter),",
                    "                    limit=limit,",
                    "                ),",
                    "            )",
                    "        )",
                ]
            )
        elif tool.name == "attio_upsert_record":
            lines.extend(
                [
                    "    def upsert_record(",
                    "        self,",
                    "        *,",
                    "        obj: AttioObjectResource,",
                    "        matching_attribute: str,",
                    "        values: object,",
                    f"    ) -> {_TOOL_OUTPUT_MODEL_BY_TOOL[tool.name]}:",
                    "        return AttioUpsertRecordToolOutput.model_validate(",
                    "            self._agent.execute_tool(",
                    f"                {tool.name!r},",
                    "                {",
                    f"                    'integrationId': {instance.id!r},",
                    "                    'objectSlug': obj.api_slug,",
                    "                    'matchingAttribute': matching_attribute,",
                    "                    'values': _json_string(values),",
                    "                },",
                    "            )",
                    "        )",
                ]
            )

    return lines


def _generate_snowflake_tools_class(instance: SnowflakeInstanceData, tools: list[ToolDefinition]) -> list[str]:
    lines = [
        "class _SnowflakeTools:",
        "    def __init__(self, agent: _SdkTerseAgent) -> None:",
        "        self._agent = agent",
    ]

    for tool in tools:
        method_name = _TOOL_METHOD_NAME_BY_TOOL[tool.name]
        lines.extend(
            [
                "",
                f"    def {method_name}(self, *, query: str) -> {_TOOL_OUTPUT_MODEL_BY_TOOL[tool.name]}:",
                f"        return {_TOOL_OUTPUT_MODEL_BY_TOOL[tool.name]}.model_validate(",
                "            self._agent.execute_tool(",
                f"                {tool.name!r},",
                f"                {{'integrationId': {instance.id!r}, 'query': query}},",
                "            )",
                "        )",
            ]
        )

    return lines


def _generate_generated_tools_class(*, has_attio_tools: bool, has_snowflake_tools: bool) -> list[str]:
    if not has_attio_tools and not has_snowflake_tools:
        return [
            "class GeneratedTools:",
            "    pass",
            "",
            "class TerseAgent(_SdkTerseAgent):",
            "    tools: GeneratedTools",
        ]

    lines = ["class GeneratedTools:", "    def __init__("]
    lines.append("        self,")
    lines.append("        *,")
    if has_attio_tools:
        lines.insert(1, "    attio: _AttioTools")
        lines.append("        attio: _AttioTools | None = None,")
    if has_snowflake_tools:
        insert_at = 1 if not has_attio_tools else 2
        lines.insert(insert_at, "    snowflake: _SnowflakeTools")
        lines.append("        snowflake: _SnowflakeTools | None = None,")
    lines.extend(["    ) -> None:"])

    if has_attio_tools:
        lines.extend(["        if attio is not None:", "            self.attio = attio"])
    if has_snowflake_tools:
        lines.extend(
            [
                "        if snowflake is not None:",
                "            self.snowflake = snowflake",
            ]
        )

    lines.extend(["", "class TerseAgent(_SdkTerseAgent):", "    tools: GeneratedTools"])
    return lines


def _generate_create_tools_functions(*, has_attio_tools: bool, has_snowflake_tools: bool) -> list[str]:
    lines = [
        "def create_tools(agent: _SdkTerseAgent) -> GeneratedTools:",
        "    allowed = {skill.integration_type for skill in agent.skills}",
    ]

    if not has_attio_tools and not has_snowflake_tools:
        lines.extend(["    _ = allowed", "    return GeneratedTools()"])
    else:
        lines.append("    return GeneratedTools(")
        if has_attio_tools:
            lines.append("        attio=_AttioTools(agent) if 'attio' in allowed else None,")
        if has_snowflake_tools:
            lines.append("        snowflake=_SnowflakeTools(agent) if 'snowflake' in allowed else None,")
        lines.append("    )")

    lines.extend(
        [
            "",
            "def attach_tools(agent: _SdkTerseAgent) -> GeneratedTools:",
            "    tools = create_tools(agent)",
            "    agent.tools = tools",
            "    return tools",
        ]
    )
    return lines


def _select_supported_tools(tools: list[ToolDefinition], integration: str) -> list[ToolDefinition]:
    ordered: list[ToolDefinition] = []
    available = {
        _canonical_tool_name(tool.name): ToolDefinition(
            name=_canonical_tool_name(tool.name),
            display_name=tool.display_name,
            description=tool.description,
            integration=tool.integration,
            is_read_only=tool.is_read_only,
            parameters=tool.parameters,
        )
        for tool in tools
        if tool.integration == integration
    }
    for supported_integration, tool_name, _method_name in _SUPPORTED_TOOL_SPECS:
        if supported_integration != integration:
            continue
        tool = available.get(tool_name)
        if tool is not None:
            ordered.append(tool)
    return ordered


def _selected_tool_output_models(tools: list[ToolDefinition]) -> list[str]:
    selected: list[str] = []
    seen: set[str] = set()
    for tool in tools:
        model_name = _TOOL_OUTPUT_MODEL_BY_TOOL.get(tool.name)
        if model_name is None or model_name in seen:
            continue
        selected.append(model_name)
        seen.add(model_name)
    return selected


def _canonical_tool_name(tool_name: str) -> str:
    return _TOOL_NAME_ALIASES.get(tool_name, tool_name)


def _to_pascal_case(value: str) -> str:
    parts = re.split(r"[^0-9A-Za-z]+", value)
    normalized = "".join(part[:1].upper() + part[1:] for part in parts if part)
    if normalized[:1].isdigit():
        return f"_{normalized}"
    return normalized


def _unique_name(candidate: str, used_names: set[str]) -> str:
    if candidate not in used_names:
        used_names.add(candidate)
        return candidate

    index = 2
    while f"{candidate}{index}" in used_names:
        index += 1

    unique_name = f"{candidate}{index}"
    used_names.add(unique_name)
    return unique_name
