"""Shared generator backend for `terse generate` and `terse init`."""

from __future__ import annotations

import re
from collections.abc import Callable
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, TypeVar, cast
from urllib.parse import quote

from ._http import request_json
from ._project import assert_project_root, read_api_key


class MissingApiKeyError(RuntimeError):
    """Raised when `TERSE_API_KEY` is missing for a command that requires it."""


@dataclass(frozen=True)
class AttioAttributeData:
    api_slug: str
    title: str = ""
    type: str = ""
    is_required: bool = False
    is_unique: bool = False


@dataclass(frozen=True)
class AttioObjectData:
    api_slug: str
    singular_noun: str
    attributes: list[AttioAttributeData] = field(default_factory=list)


@dataclass(frozen=True)
class AttioInstanceData:
    id: str
    display_name: str
    objects: list[AttioObjectData] = field(default_factory=list)


@dataclass(frozen=True)
class SnowflakeInstanceData:
    id: str
    display_name: str


@dataclass(frozen=True)
class ToolDefinition:
    name: str
    display_name: str
    description: str
    integration: str
    is_read_only: bool
    supports_approval: bool = False
    parameters: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class CodegenInput:
    attio: list[AttioInstanceData] = field(default_factory=list)
    snowflake: list[SnowflakeInstanceData] = field(default_factory=list)
    tools: list[ToolDefinition] = field(default_factory=list)


@dataclass(frozen=True)
class GenerateResult:
    project_dir: Path
    output_path: Path
    summary_lines: list[str]


T = TypeVar("T")
_SUPPORTED_TOOL_SPECS: tuple[tuple[str, str, str], ...] = (
    ("attio", "attio_list_objects", "list_objects"),
    ("attio", "attio_query_records", "query_records"),
    ("attio", "attio_upsert_record", "upsert_record"),
    ("snowflake", "snowflakeExecuteQuery", "execute_query"),
    ("snowflake", "snowflakeExplainQuery", "explain_query"),
)
_SUPPORTED_TOOL_NAMES = {tool_name for _, tool_name, _ in _SUPPORTED_TOOL_SPECS}
_TOOL_METHOD_NAME_BY_TOOL = {tool_name: method_name for _, tool_name, method_name in _SUPPORTED_TOOL_SPECS}
_TOOL_NAME_ALIASES = {
    "snowflake_execute_query": "snowflakeExecuteQuery",
    "snowflake_explain_query": "snowflakeExplainQuery",
}
_TOOL_OUTPUT_MODEL_BY_TOOL = {
    "attio_list_objects": "AttioListObjectsToolOutput",
    "attio_query_records": "AttioQueryRecordsToolOutput",
    "attio_upsert_record": "AttioUpsertRecordToolOutput",
    "snowflakeExecuteQuery": "SnowflakeExecuteQueryToolOutput",
    "snowflakeExplainQuery": "SnowflakeExplainQueryToolOutput",
}


def generate_project(project_dir: Path | None = None) -> GenerateResult:
    """Generate Python helper bindings for the project's active integrations."""

    resolved_dir = assert_project_root(project_dir)
    api_key = read_api_key(resolved_dir)
    if not api_key:
        raise MissingApiKeyError(
            "Missing TERSE_API_KEY in .env.\nCreate a project with `terse init` or add TERSE_API_KEY to your .env file."
        )

    active_types = request_json("/integrations/active", api_key)
    active_set = {str(item).lower() for item in active_types} if isinstance(active_types, list) else set()

    codegen_input = _build_codegen_input(active_set, api_key)
    output_path = write_generated_module(resolved_dir, render_generated_module(codegen_input))

    return GenerateResult(
        project_dir=resolved_dir,
        output_path=output_path,
        summary_lines=_build_summary_lines(codegen_input),
    )


def render_generated_module(codegen_input: CodegenInput | None = None) -> str:
    """Render the generated Python helper module."""

    input_data = codegen_input or CodegenInput()
    exported_names: list[str] = [
        "Schedule",
        "GeneratedTools",
        "create_tools",
        "attach_tools",
        "TerseAgent",
    ]
    attio_tools = _select_supported_tools(input_data.tools, "attio")
    snowflake_tools = _select_supported_tools(input_data.tools, "snowflake")
    tool_output_models = _selected_tool_output_models(attio_tools + snowflake_tools)
    exported_names.extend(tool_output_models)

    has_attio = bool(input_data.attio)
    has_attio_attrs = has_attio and any(obj.attributes for inst in input_data.attio for obj in inst.objects)
    has_tools = bool(attio_tools or snowflake_tools)

    # --- Collect approvable tool names for Literal generation ---
    all_approvable: list[str] = []
    attio_approvable = _build_approvable_tool_names(input_data.tools, "attio")
    snowflake_approvable = _build_approvable_tool_names(input_data.tools, "snowflake")
    all_approvable.extend(attio_approvable)
    all_approvable.extend(snowflake_approvable)

    lines = [
        '"""',
        "Generated by `terse generate`. Do not edit manually.",
        "",
        "Type checking:",
        "    uv run ty check src/",
        '"""',
        "",
        "from __future__ import annotations",
    ]

    # --- typing imports ---
    typing_names: list[str] = []
    if has_attio_attrs:
        typing_names.extend(["Any", "Generic", "TypeVar", "TypedDict", "cast"])
    if all_approvable or has_attio_attrs:
        typing_names.append("Literal")
    if typing_names:
        lines.extend(["", f"from typing import {', '.join(sorted(set(typing_names)))}"])

    # --- pydantic imports ---
    if has_attio:
        pydantic_names = ["BaseModel", "ConfigDict"]
        if has_tools:
            pydantic_names.append("validate_call")
        lines.extend(["", f"from pydantic import {', '.join(pydantic_names)}"])
    elif has_tools:
        lines.extend(["", "from pydantic import validate_call"])
    if attio_tools:
        lines.extend(["", "import json"])

    # --- SDK imports ---
    sdk_imports: list[str] = ["SkillConfig", "TerseAgent as _SdkTerseAgent", "TriggerConfig"]
    if has_attio_attrs and attio_tools:
        sdk_imports.extend([
            "AttioTypedQueryResult",
            "AttioTypedRecord",
            "AttioTypedUpsertResult",
        ])
    if tool_output_models:
        sdk_imports.extend(tool_output_models)

    lines.extend(
        [
            "",
            "from terse_sdk import (",
            *[f"    {name}," for name in sdk_imports],
            ")",
        ]
    )

    lines.extend(
        [
            "",
            "",
            "def _compact_dict(**values: object) -> dict[str, object]:",
            '    """Drop None values while preserving falsey config values like False and []."""',
            "",
            "    return {key: value for key, value in values.items() if value is not None}",
        ]
    )

    sections: list[list[str]] = []

    # --- Tool name Literals ---
    tool_literals_section = _generate_tool_name_literals(
        attio_approvable, snowflake_approvable, all_approvable,
    )
    if tool_literals_section:
        sections.append(tool_literals_section)
        if attio_approvable:
            exported_names.append("AttioToolNames")
        if snowflake_approvable:
            exported_names.append("SnowflakeToolNames")
        if all_approvable:
            exported_names.append("AllToolNames")

    attio_section = _generate_attio_section(
        input_data.attio,
        tool_names_type="AttioToolNames" if attio_approvable else None,
    )
    if attio_section:
        sections.append(attio_section)
        exported_names.extend(["AttioAttributeDefinition", "AttioObjectResource", "AttioObject", "Attio"])
        # Export per-object TypedDicts and Literal slugs
        if has_attio_attrs:
            for obj in input_data.attio[0].objects:
                if obj.attributes:
                    pascal = _to_pascal_case(obj.singular_noun or obj.api_slug) or "Object"
                    exported_names.extend([
                        f"{pascal}RecordValues",
                        f"{pascal}InputValues",
                        f"{pascal}Filter",
                        f"{pascal}AttributeSlug",
                    ])

    snowflake_section = _generate_snowflake_section(
        input_data.snowflake,
        tool_names_type="SnowflakeToolNames" if snowflake_approvable else None,
    )
    if snowflake_section:
        sections.append(snowflake_section)
        exported_names.append("Snowflake")

    sections.append(_generate_schedule_section())
    sections.append(_generate_tools_section(input_data, attio_tools, snowflake_tools))

    for section in sections:
        lines.extend(["", "", *section])

    lines.extend(["", "", f"__all__ = {exported_names!r}", ""])
    return "\n".join(lines)


def write_generated_module(project_dir: Path, content: str) -> Path:
    """Write the generated helper module into the project's src directory."""

    output_path = project_dir / "src" / "terse_generated.py"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")
    return output_path


def _build_codegen_input(active_set: set[str], api_key: str) -> CodegenInput:
    return CodegenInput(
        attio=(_safe_fetch(lambda: _fetch_attio_instances(api_key)) if "attio" in active_set else []),
        snowflake=(_safe_fetch(lambda: _fetch_snowflake_instances(api_key)) if "snowflake" in active_set else []),
        tools=_safe_fetch(lambda: _fetch_tool_definitions(api_key, active_set)),
    )


def _safe_fetch(fetcher: Callable[[], list[T]]) -> list[T]:
    try:
        return fetcher()
    except Exception:
        return []


def _as_dict(value: object) -> dict[str, Any] | None:
    if isinstance(value, dict):
        return cast(dict[str, Any], value)
    return None


def _as_list(value: object) -> list[Any]:
    if isinstance(value, list):
        return cast(list[Any], value)
    return []


def _fetch_attio_instances(api_key: str) -> list[AttioInstanceData]:
    raw_instances = _as_list(request_json("/attio/integrations", api_key))
    instances: list[AttioInstanceData] = []

    for integration in raw_instances:
        integration_data = _as_dict(integration)
        if integration_data is None:
            continue

        integration_id = str(integration_data.get("id", ""))
        raw_objects = _safe_request_json(
            f"/attio/integrations/{quote(integration_id, safe='')}/objects",
            api_key,
        )
        objects: list[AttioObjectData] = []
        for raw_object in _as_list(raw_objects):
            obj_data = _as_dict(raw_object)
            if obj_data is None:
                continue
            api_slug = str(obj_data.get("api_slug", ""))
            if not api_slug:
                continue
            attributes = [
                AttioAttributeData(
                    api_slug=str(attr_dict.get("api_slug", "")),
                    title=str(attr_dict.get("title", "")),
                    type=str(attr_dict.get("type", "")),
                    is_required=bool(attr_dict.get("is_required")),
                    is_unique=bool(attr_dict.get("is_unique")),
                )
                for raw_attr in _as_list(obj_data.get("attributes"))
                if (attr_dict := _as_dict(raw_attr)) is not None and str(attr_dict.get("api_slug", ""))
            ]
            objects.append(
                AttioObjectData(
                    api_slug=api_slug,
                    singular_noun=str(obj_data.get("singular_noun", "")),
                    attributes=attributes,
                )
            )
        instances.append(
            AttioInstanceData(
                id=integration_id,
                display_name=str(integration_data.get("workspaceName") or integration_id),
                objects=objects,
            )
        )

    return instances


def _fetch_snowflake_instances(api_key: str) -> list[SnowflakeInstanceData]:
    raw_instances = _as_list(request_json("/snowflake/integrations", api_key))
    return [
        SnowflakeInstanceData(
            id=str((_as_dict(integration) or {}).get("id", "")),
            display_name=str(
                (_as_dict(integration) or {}).get("accountIdentifier") or (_as_dict(integration) or {}).get("id") or ""
            ),
        )
        for integration in raw_instances
        if _as_dict(integration) is not None
    ]


def _fetch_tool_definitions(api_key: str, active_set: set[str]) -> list[ToolDefinition]:
    raw_payload = _as_dict(request_json("/sdk/tool-definitions", api_key))
    raw_tools = _as_list(raw_payload.get("tools") if raw_payload is not None else None)
    definitions: list[ToolDefinition] = []

    for raw_tool in raw_tools:
        tool_data = _as_dict(raw_tool)
        if tool_data is None:
            continue

        integration = str(tool_data.get("integration", "")).lower()
        tool_name = _canonical_tool_name(str(tool_data.get("name", "")))
        if integration not in active_set or tool_name not in _SUPPORTED_TOOL_NAMES:
            continue

        definitions.append(
            ToolDefinition(
                name=tool_name,
                display_name=str(tool_data.get("displayName") or tool_name),
                description=str(tool_data.get("description") or ""),
                integration=integration,
                is_read_only=bool(tool_data.get("isReadOnly")),
                supports_approval=bool(tool_data.get("supportsApproval")),
                parameters=_as_dict(tool_data.get("parameters")) or {},
            )
        )

    return definitions


def _safe_request_json(path: str, api_key: str) -> object | None:
    try:
        return request_json(path, api_key)
    except Exception:
        return None


def _is_attio_multi_value(attr: AttioAttributeData) -> bool:
    """Check if an Attio attribute is multi-valued."""
    slug = attr.api_slug.lower()
    type_ = attr.type.lower()
    return (
        "multi" in type_
        or "array" in type_
        or "list" in type_
        or slug in ("email_addresses", "domains", "phone_numbers", "social_profiles", "links", "tags")
        or slug.endswith("_addresses")
        or slug.endswith("_ids")
    )


def _attio_base_python_type(attr: AttioAttributeData) -> str:
    """Map an Attio attribute type to a Python type string."""
    type_ = attr.type.lower()
    slug = attr.api_slug.lower()
    if "checkbox" in type_ or "boolean" in type_:
        return "bool"
    if any(k in type_ for k in ("number", "currency", "rating", "percent")):
        return "float"
    if any(
        k in type_
        for k in ("date", "time", "email", "domain", "phone", "url", "select", "status", "text", "string", "name")
    ):
        return "str"
    if any(k in type_ for k in ("location", "address", "reference", "record", "actor")):
        return "dict[str, Any]"
    if slug in ("email_addresses", "domains", "phone_numbers", "name"):
        return "str"
    return "Any"


def _attio_record_python_type(attr: AttioAttributeData) -> str:
    """Python type for record output (multi-value → list[T])."""
    base = _attio_base_python_type(attr)
    if not _is_attio_multi_value(attr):
        return base
    return f"list[{base}]"


def _attio_input_python_type(attr: AttioAttributeData) -> str:
    """Python type for input values (multi-value → T | list[T])."""
    base = _attio_base_python_type(attr)
    if not _is_attio_multi_value(attr):
        return base
    return f"{base} | list[{base}]"


def _attio_filter_python_type(attr: AttioAttributeData) -> str:
    """Python type for filter values (input shorthand or operator dict)."""
    value_type = _attio_input_python_type(attr)
    if value_type in ("Any", "dict[str, Any]"):
        return "dict[str, Any]"
    return f"{value_type} | dict[str, Any]"


def _build_approvable_tool_names(tools: list[ToolDefinition], integration: str) -> list[str]:
    """Return sorted tool names that are approvable for a given integration."""
    return sorted(
        tool.name
        for tool in tools
        if tool.integration == integration and (not tool.is_read_only or tool.supports_approval)
    )


def _build_summary_lines(codegen_input: CodegenInput) -> list[str]:
    lines = [f"Attio ({instance.display_name}) — {len(instance.objects)} objects" for instance in codegen_input.attio]
    lines.extend(f"Snowflake ({instance.display_name})" for instance in codegen_input.snowflake)
    lines.append("Schedule trigger")
    return lines


def _generate_attio_section(instances: list[AttioInstanceData], tool_names_type: str | None = None) -> list[str]:
    if not instances:
        return []

    instance = instances[0]
    has_attrs = any(obj.attributes for obj in instance.objects)
    lines = ["# === Attio ===", ""]

    # --- Per-object TypedDicts, Literal slugs ---
    if has_attrs:
        for obj in instance.objects:
            if not obj.attributes:
                continue
            lines.extend(_generate_attio_object_types(obj))
            lines.append("")

    # --- AttioAttributeDefinition, AttioObjectResource, AttioObject ---
    lines.extend(_generate_attio_namespace(instance.objects, has_attrs))

    # --- Attio skill ---
    obj_type = "AttioObjectResource[Any, Any, Any, Any]" if has_attrs else "AttioObjectResource"
    skill_return_type = f"SkillConfig[{tool_names_type}]" if tool_names_type else "SkillConfig[str]"
    lines.extend([
        "",
        "class Attio:",
        "    @staticmethod",
        f"    def skill(obj: {obj_type} | None = None) -> {skill_return_type}:",
        (
            "        return SkillConfig("
            f"integration_id={instance.id!r}, "
            "integration_type='attio', "
            "config_type='attio_output', "
            "config=_compact_dict(objectSlug=obj.api_slug if obj else None)"
            ")"
        ),
    ])

    # --- Multi-value registry + flattening ---
    if has_attrs:
        lines.extend(["", ""])
        lines.extend(_generate_attio_flattening(instance.objects))

    return lines


def _generate_attio_object_types(obj: AttioObjectData) -> list[str]:
    """Generate TypedDicts and Literal slug type for a single Attio object."""
    pascal = _to_pascal_case(obj.singular_noun or obj.api_slug) or "Object"
    lines: list[str] = []

    # RecordValues TypedDict (multi-value → list[T])
    lines.append(f"class {pascal}RecordValues(TypedDict, total=False):")
    if not obj.attributes:
        lines.append("    pass")
    else:
        for attr in obj.attributes:
            py_type = _attio_record_python_type(attr)
            lines.append(f"    {attr.api_slug}: {py_type}")

    lines.append("")

    # InputValues TypedDict (multi-value → T | list[T])
    lines.append(f"class {pascal}InputValues(TypedDict, total=False):")
    if not obj.attributes:
        lines.append("    pass")
    else:
        for attr in obj.attributes:
            py_type = _attio_input_python_type(attr)
            lines.append(f"    {attr.api_slug}: {py_type}")

    lines.append("")

    # AttributeSlug Literal
    slugs = [attr.api_slug for attr in obj.attributes]
    if slugs:
        slug_union = ", ".join(repr(s) for s in slugs)
        lines.append(f"{pascal}AttributeSlug = Literal[{slug_union}]")
    else:
        lines.append(f"{pascal}AttributeSlug = Literal['']")

    lines.append("")

    filter_name = f"{pascal}Filter"
    lines.append(f"class {filter_name}(TypedDict, total=False):")
    if not obj.attributes:
        lines.append("    pass")
    else:
        for attr in obj.attributes:
            filter_type = _attio_filter_python_type(attr)
            lines.append(f"    {attr.api_slug}: {filter_type}")

    lines.append("")
    lines.append(f"{filter_name}.__annotations__['$and'] = list['{filter_name}']")
    lines.append(f"{filter_name}.__annotations__['$or'] = list['{filter_name}']")

    return lines


def _generate_attio_namespace(objects: list[AttioObjectData], has_attrs: bool) -> list[str]:
    lines = [
        "class AttioAttributeDefinition(BaseModel):",
        "    model_config = ConfigDict(frozen=True)",
        "    api_slug: str",
        "    title: str = ''",
        "    type: str = ''",
        "    is_required: bool = False",
        "    is_unique: bool = False",
        "",
    ]

    if has_attrs:
        lines.extend([
            "_TSlug = TypeVar('_TSlug', bound=str)",
            "_TRecordValues = TypeVar('_TRecordValues')",
            "_TInputValues = TypeVar('_TInputValues')",
            "_TFilterValues = TypeVar('_TFilterValues')",
            "",
            "class AttioObjectResource(BaseModel, Generic[_TSlug, _TRecordValues, _TInputValues, _TFilterValues]):",
            "    model_config = ConfigDict(frozen=True)",
            "    api_slug: str",
            "    name: str",
            "    attributes: tuple[AttioAttributeDefinition, ...] = ()",
            "",
        ])
    else:
        lines.extend([
            "class AttioObjectResource(BaseModel):",
            "    model_config = ConfigDict(frozen=True)",
            "    api_slug: str",
            "    name: str",
            "    attributes: tuple[AttioAttributeDefinition, ...] = ()",
            "",
        ])

    if not objects:
        lines.extend(["class AttioObject:", "    pass"])
        return lines

    lines.append("class AttioObject:")
    used_names: set[str] = set()
    for obj in objects:
        static_name = _unique_name(_to_pascal_case(obj.singular_noun or obj.api_slug) or "Object", used_names)
        if has_attrs and obj.attributes:
            pascal = _to_pascal_case(obj.singular_noun or obj.api_slug) or "Object"
            type_annotation = (
                f"AttioObjectResource[{pascal}AttributeSlug, {pascal}RecordValues, "
                f"{pascal}InputValues, {pascal}Filter]"
            )
            attr_tuple = _render_attribute_tuple(obj.attributes)
            lines.append(
                f"    {static_name}: {type_annotation} = "
                f"AttioObjectResource(api_slug={obj.api_slug!r}, name={obj.singular_noun!r}, "
                f"attributes={attr_tuple})"
            )
        else:
            lines.append(
                f"    {static_name} = AttioObjectResource(api_slug={obj.api_slug!r}, "
                f"name={obj.singular_noun!r})"
            )
    return lines


def _generate_attio_flattening(objects: list[AttioObjectData]) -> list[str]:
    """Generate multi-value registry, metadata keys, and flattening helpers."""
    lines: list[str] = []

    # Multi-value attribute registry
    lines.append("_ATTIO_MULTI_VALUE_ATTRS: dict[str, frozenset[str]] = {")
    for obj in objects:
        multi_slugs = [attr.api_slug for attr in obj.attributes if _is_attio_multi_value(attr)]
        if multi_slugs:
            slug_set = ", ".join(repr(s) for s in multi_slugs)
            lines.append(f"    {obj.api_slug!r}: frozenset({{{slug_set}}}),")
    lines.append("}")
    lines.append("")

    # Metadata keys to skip
    lines.append(
        "_ATTIO_METADATA_KEYS = frozenset({"
        "'active_from', 'active_until', 'attribute_type', 'created_by_actor'"
        "})"
    )
    lines.append("")

    # Leaf value extraction
    lines.extend([
        "def _flatten_attio_leaf(value: Any) -> Any:",
        "    if isinstance(value, dict):",
        "        for key in ('value', 'domain', 'email_address', 'phone_number',",
        "                     'original_phone_number', 'full_name', 'first_name', 'url'):",
        "            if key in value:",
        "                return value[key]",
        "    return value",
        "",
    ])

    # Record flattening
    lines.extend([
        "def _flatten_attio_record(obj_slug: str, raw: object) -> AttioTypedRecord[Any]:",
        "    multi = _ATTIO_MULTI_VALUE_ATTRS.get(obj_slug, frozenset())",
        "    flat: dict[str, Any] = {}",
        "    raw_values = getattr(raw, 'values', None) or {}",
        "    for key, val in raw_values.items():",
        "        if key in _ATTIO_METADATA_KEYS:",
        "            continue",
        "        if isinstance(val, list):",
        "            leaves = [_flatten_attio_leaf(item) for item in val]",
        "            flat[key] = leaves if key in multi else (leaves[0] if leaves else None)",
        "        else:",
        "            flat[key] = _flatten_attio_leaf(val)",
        "    return AttioTypedRecord(",
        "        values=flat,",
        "        id=getattr(raw, 'id', None),",
        "        created_at=getattr(raw, 'created_at', None),",
        "        web_url=getattr(raw, 'web_url', None),",
        "    )",
    ])

    return lines


def _render_attribute_tuple(attributes: list[AttioAttributeData]) -> str:
    """Render a tuple of AttioAttributeDefinition(...) calls."""
    if not attributes:
        return "()"
    parts = []
    for attr in attributes:
        args = [f"api_slug={attr.api_slug!r}"]
        if attr.title:
            args.append(f"title={attr.title!r}")
        if attr.type:
            args.append(f"type={attr.type!r}")
        if attr.is_required:
            args.append("is_required=True")
        if attr.is_unique:
            args.append("is_unique=True")
        parts.append(f"AttioAttributeDefinition({', '.join(args)})")
    return f"({', '.join(parts)},)"


def _generate_tool_name_literals(
    attio_names: list[str], snowflake_names: list[str], all_names: list[str],
) -> list[str]:
    """Generate Literal type aliases for approvable tool names."""
    if not all_names:
        return []

    lines = ["# === Tool name types ===", ""]
    if attio_names:
        union = ", ".join(repr(n) for n in attio_names)
        lines.append(f"AttioToolNames = Literal[{union}]")
    if snowflake_names:
        union = ", ".join(repr(n) for n in snowflake_names)
        lines.append(f"SnowflakeToolNames = Literal[{union}]")
    if all_names:
        union = ", ".join(repr(n) for n in sorted(all_names))
        lines.append(f"AllToolNames = Literal[{union}]")
    return lines


def _generate_snowflake_section(
    instances: list[SnowflakeInstanceData],
    tool_names_type: str | None = None,
) -> list[str]:
    if not instances:
        return []

    instance = instances[0]
    skill_return_type = f"SkillConfig[{tool_names_type}]" if tool_names_type else "SkillConfig[str]"
    return [
        "# === Snowflake ===",
        "",
        "class Snowflake:",
        "    @staticmethod",
        f"    def skill() -> {skill_return_type}:",
        (
            "        return SkillConfig("
            f"integration_id={instance.id!r}, "
            "integration_type='snowflake', "
            "config_type='snowflake_output', "
            "config=_compact_dict()"
            ")"
        ),
    ]


def _generate_schedule_section() -> list[str]:
    return [
        "# === Schedule ===",
        "",
        "class Schedule:",
        "    @staticmethod",
        "    def cron(expression: str) -> TriggerConfig:",
        (
            "        return TriggerConfig("
            "integration_id='system', "
            "integration_type='cron_job', "
            "config_type='time_trigger', "
            "config=_compact_dict(cronExpression=expression)"
            ")"
        ),
    ]


def _generate_tools_section(
    codegen_input: CodegenInput,
    attio_tools: list[ToolDefinition],
    snowflake_tools: list[ToolDefinition],
) -> list[str]:
    lines = ["# === Deterministic tools ===", ""]

    if attio_tools:
        lines.extend(_generate_tool_json_helpers())
        lines.extend(["", ""])

    if codegen_input.attio and attio_tools:
        lines.extend(_generate_attio_tools_class(codegen_input.attio[0], attio_tools))
        lines.extend(["", ""])

    if codegen_input.snowflake and snowflake_tools:
        lines.extend(_generate_snowflake_tools_class(codegen_input.snowflake[0], snowflake_tools))
        lines.extend(["", ""])

    lines.extend(
        _generate_generated_tools_class(
            has_attio_tools=bool(codegen_input.attio and attio_tools),
            has_snowflake_tools=bool(codegen_input.snowflake and snowflake_tools),
        )
    )
    lines.extend(["", ""])
    lines.extend(
        _generate_create_tools_functions(
            has_attio_tools=bool(codegen_input.attio and attio_tools),
            has_snowflake_tools=bool(codegen_input.snowflake and snowflake_tools),
        )
    )
    return lines


def _generate_tool_json_helpers() -> list[str]:
    return [
        "def _json_string(value: object | None) -> str | None:",
        "    if value is None:",
        "        return None",
        "    if isinstance(value, str):",
        "        return value",
        "    return json.dumps(value, separators=(',', ':'), sort_keys=True)",
    ]


def _generate_attio_tools_class(instance: AttioInstanceData, tools: list[ToolDefinition]) -> list[str]:
    has_attrs = any(obj.attributes for obj in instance.objects)
    lines = [
        "class _AttioTools:",
        "    def __init__(self, agent: _SdkTerseAgent) -> None:",
        "        self._agent = agent",
    ]

    for tool in tools:
        lines.extend([""])
        if tool.name == "attio_list_objects":
            lines.extend(
                [
                    f"    def list_objects(self) -> {_TOOL_OUTPUT_MODEL_BY_TOOL[tool.name]}:",
                    "        return AttioListObjectsToolOutput.model_validate(",
                    f"            self._agent.execute_tool({tool.name!r}, {{'integrationId': {instance.id!r}}})",
                    "        )",
                ]
            )
        elif tool.name == "attio_query_records":
            if has_attrs:
                lines.extend(
                    [
                        "    def query_records(",
                        "        self,",
                        "        obj: AttioObjectResource[Any, _TRecordValues, Any, _TFilterValues],",
                        "        filter: _TFilterValues | None = None,",
                        "        limit: int | None = None,",
                        "    ) -> AttioTypedQueryResult[_TRecordValues]:",
                        "        raw = AttioQueryRecordsToolOutput.model_validate(",
                        "            self._agent.execute_tool(",
                        f"                {tool.name!r},",
                        "                _compact_dict(",
                        f"                    integrationId={instance.id!r},",
                        "                    objectSlug=obj.api_slug,",
                        "                    filter=_json_string(filter),",
                        "                    limit=limit,",
                        "                ),",
                        "            )",
                        "        )",
                        "        return AttioTypedQueryResult(",
                        "            success=raw.success, count=raw.count,",
                        "            records=[cast(AttioTypedRecord[_TRecordValues], _flatten_attio_record(obj.api_slug, r)) for r in raw.records],",
                        "        )",
                    ]
                )
            else:
                lines.extend(
                    [
                        "    def query_records(",
                        "        self,",
                        "        obj: AttioObjectResource,",
                        "        filter: object | None = None,",
                        "        limit: int | None = None,",
                        f"    ) -> {_TOOL_OUTPUT_MODEL_BY_TOOL[tool.name]}:",
                        "        return AttioQueryRecordsToolOutput.model_validate(",
                        "            self._agent.execute_tool(",
                        f"                {tool.name!r},",
                        "                _compact_dict(",
                        f"                    integrationId={instance.id!r},",
                        "                    objectSlug=obj.api_slug,",
                        "                    filter=_json_string(filter),",
                        "                    limit=limit,",
                        "                ),",
                        "            )",
                        "        )",
                    ]
                )
        elif tool.name == "attio_upsert_record":
            if has_attrs:
                lines.extend(
                    [
                        "    def upsert_record(",
                        "        self,",
                        "        obj: AttioObjectResource[_TSlug, _TRecordValues, _TInputValues, Any],",
                        "        matching_attribute: _TSlug,",
                        "        records: list[_TInputValues],",
                        "    ) -> AttioTypedUpsertResult[_TRecordValues]:",
                        "        raw = AttioUpsertRecordToolOutput.model_validate(",
                        "            self._agent.execute_tool(",
                        f"                {tool.name!r},",
                        "                {",
                        f"                    'integrationId': {instance.id!r},",
                        "                    'objectSlug': obj.api_slug,",
                        "                    'matchingAttribute': matching_attribute,",
                        "                    'records': records,",
                        "                },",
                        "            )",
                        "        )",
                        "        return AttioTypedUpsertResult(",
                        "            success=raw.success,",
                        "            records=[cast(AttioTypedRecord[_TRecordValues], _flatten_attio_record(obj.api_slug, r)) for r in (raw.records or [])],",
                        "            count=int(raw.count or 0),",
                        "            requested_count=int(raw.requestedCount or 0),",
                        "            success_count=int(raw.successCount or 0),",
                        "            failure_count=int(raw.failureCount or 0),",
                        "            partial=raw.partial or False,",
                        "            errors=raw.errors or [],",
                        "        )",
                    ]
                )
            else:
                lines.extend(
                    [
                        "    def upsert_record(",
                        "        self,",
                        "        obj: AttioObjectResource,",
                        "        matching_attribute: str,",
                        "        records: list[object],",
                        f"    ) -> {_TOOL_OUTPUT_MODEL_BY_TOOL[tool.name]}:",
                        "        return AttioUpsertRecordToolOutput.model_validate(",
                        "            self._agent.execute_tool(",
                        f"                {tool.name!r},",
                        "                {",
                        f"                    'integrationId': {instance.id!r},",
                        "                    'objectSlug': obj.api_slug,",
                        "                    'matchingAttribute': matching_attribute,",
                        "                    'records': records,",
                        "                },",
                        "            )",
                        "        )",
                    ]
                )

    return lines


def _generate_snowflake_tools_class(instance: SnowflakeInstanceData, tools: list[ToolDefinition]) -> list[str]:
    lines = [
        "class _SnowflakeTools:",
        "    def __init__(self, agent: _SdkTerseAgent) -> None:",
        "        self._agent = agent",
    ]

    for tool in tools:
        method_name = _TOOL_METHOD_NAME_BY_TOOL[tool.name]
        lines.extend(
            [
                "",
                f"    def {method_name}(self, query: str) -> {_TOOL_OUTPUT_MODEL_BY_TOOL[tool.name]}:",
                f"        return {_TOOL_OUTPUT_MODEL_BY_TOOL[tool.name]}.model_validate(",
                "            self._agent.execute_tool(",
                f"                {tool.name!r},",
                f"                {{'integrationId': {instance.id!r}, 'query': query}},",
                "            )",
                "        )",
            ]
        )

    return lines


def _generate_generated_tools_class(*, has_attio_tools: bool, has_snowflake_tools: bool) -> list[str]:
    if not has_attio_tools and not has_snowflake_tools:
        return [
            "class GeneratedTools:",
            "    pass",
            "",
            "class TerseAgent(_SdkTerseAgent):",
            "    tools: GeneratedTools",
        ]

    lines = ["class GeneratedTools:", "    def __init__("]
    lines.append("        self,")
    if has_attio_tools:
        lines.insert(1, "    attio: _AttioTools")
        lines.append("        attio: _AttioTools | None = None,")
    if has_snowflake_tools:
        insert_at = 1 if not has_attio_tools else 2
        lines.insert(insert_at, "    snowflake: _SnowflakeTools")
        lines.append("        snowflake: _SnowflakeTools | None = None,")
    lines.extend(["    ) -> None:"])

    if has_attio_tools:
        lines.extend(["        if attio is not None:", "            self.attio = attio"])
    if has_snowflake_tools:
        lines.extend(
            [
                "        if snowflake is not None:",
                "            self.snowflake = snowflake",
            ]
        )

    lines.extend(["", "class TerseAgent(_SdkTerseAgent):", "    tools: GeneratedTools"])
    return lines


def _generate_create_tools_functions(*, has_attio_tools: bool, has_snowflake_tools: bool) -> list[str]:
    lines = [
        "def create_tools(agent: _SdkTerseAgent) -> GeneratedTools:",
        "    allowed = {skill.integration_type for skill in agent.skills}",
    ]

    if not has_attio_tools and not has_snowflake_tools:
        lines.extend(["    _ = allowed", "    return GeneratedTools()"])
    else:
        lines.append("    return GeneratedTools(")
        if has_attio_tools:
            lines.append("        attio=_AttioTools(agent) if 'attio' in allowed else None,")
        if has_snowflake_tools:
            lines.append("        snowflake=_SnowflakeTools(agent) if 'snowflake' in allowed else None,")
        lines.append("    )")

    lines.extend(
        [
            "",
            "def attach_tools(agent: _SdkTerseAgent) -> GeneratedTools:",
            "    tools = create_tools(agent)",
            "    agent.tools = tools",
            "    return tools",
        ]
    )
    return lines


def _select_supported_tools(tools: list[ToolDefinition], integration: str) -> list[ToolDefinition]:
    ordered: list[ToolDefinition] = []
    available = {
        _canonical_tool_name(tool.name): ToolDefinition(
            name=_canonical_tool_name(tool.name),
            display_name=tool.display_name,
            description=tool.description,
            integration=tool.integration,
            is_read_only=tool.is_read_only,
            supports_approval=tool.supports_approval,
            parameters=tool.parameters,
        )
        for tool in tools
        if tool.integration == integration
    }
    for supported_integration, tool_name, _method_name in _SUPPORTED_TOOL_SPECS:
        if supported_integration != integration:
            continue
        tool = available.get(tool_name)
        if tool is not None:
            ordered.append(tool)
    return ordered


def _selected_tool_output_models(tools: list[ToolDefinition]) -> list[str]:
    selected: list[str] = []
    seen: set[str] = set()
    for tool in tools:
        model_name = _TOOL_OUTPUT_MODEL_BY_TOOL.get(tool.name)
        if model_name is None or model_name in seen:
            continue
        selected.append(model_name)
        seen.add(model_name)
    return selected


def _canonical_tool_name(tool_name: str) -> str:
    return _TOOL_NAME_ALIASES.get(tool_name, tool_name)


def _to_pascal_case(value: str) -> str:
    parts = re.split(r"[^0-9A-Za-z]+", value)
    normalized = "".join(part[:1].upper() + part[1:] for part in parts if part)
    if normalized[:1].isdigit():
        return f"_{normalized}"
    return normalized


def _unique_name(candidate: str, used_names: set[str]) -> str:
    if candidate not in used_names:
        used_names.add(candidate)
        return candidate

    index = 2
    while f"{candidate}{index}" in used_names:
        index += 1

    unique_name = f"{candidate}{index}"
    used_names.add(unique_name)
    return unique_name
