"""Shared generator backend for `terse generate` and `terse init`."""

from __future__ import annotations

import re
from collections.abc import Callable
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, TypeVar, cast
from urllib.parse import quote

from ._http import request_json
from ._project import assert_project_root, read_api_key


class MissingApiKeyError(RuntimeError):
    """Raised when `TERSE_API_KEY` is missing for a command that requires it."""


@dataclass(frozen=True)
class AttioObjectData:
    api_slug: str
    singular_noun: str


@dataclass(frozen=True)
class AttioInstanceData:
    id: str
    display_name: str
    objects: list[AttioObjectData] = field(default_factory=list)


@dataclass(frozen=True)
class SnowflakeInstanceData:
    id: str
    display_name: str


@dataclass(frozen=True)
class CodegenInput:
    attio: list[AttioInstanceData] = field(default_factory=list)
    snowflake: list[SnowflakeInstanceData] = field(default_factory=list)


@dataclass(frozen=True)
class GenerateResult:
    project_dir: Path
    output_path: Path
    summary_lines: list[str]


T = TypeVar("T")


def generate_project(project_dir: Path | None = None) -> GenerateResult:
    """Generate Python helper bindings for the project's active integrations."""

    resolved_dir = assert_project_root(project_dir)
    api_key = read_api_key(resolved_dir)
    if not api_key:
        raise MissingApiKeyError(
            "Missing TERSE_API_KEY in .env.\nCreate a project with `terse init` or add TERSE_API_KEY to your .env file."
        )

    active_types = request_json("/integrations/active", api_key)
    active_set = {str(item).lower() for item in active_types} if isinstance(active_types, list) else set()

    codegen_input = _build_codegen_input(active_set, api_key)
    output_path = write_generated_module(resolved_dir, render_generated_module(codegen_input))

    return GenerateResult(
        project_dir=resolved_dir,
        output_path=output_path,
        summary_lines=_build_summary_lines(codegen_input),
    )


def render_generated_module(codegen_input: CodegenInput | None = None) -> str:
    """Render the generated Python helper module."""

    input_data = codegen_input or CodegenInput()
    exported_names = ["Schedule"]
    lines = [
        '"""Generated by `terse generate`. Do not edit manually."""',
        "",
        "from __future__ import annotations",
    ]

    if input_data.attio:
        lines.extend(["", "from dataclasses import dataclass", "from types import SimpleNamespace"])

    lines.extend(
        [
            "",
            "from terse_sdk import SkillConfig, TriggerConfig",
            "",
            "",
            "def _compact_dict(**values: object) -> dict[str, object]:",
            '    """Drop None values while preserving falsey config values like False and []."""',
            "",
            "    return {key: value for key, value in values.items() if value is not None}",
        ]
    )

    sections: list[list[str]] = []

    attio_section = _generate_attio_section(input_data.attio)
    if attio_section:
        sections.append(attio_section)
        exported_names.extend(["AttioObjectResource", "AttioObject", "Attio"])

    snowflake_section = _generate_snowflake_section(input_data.snowflake)
    if snowflake_section:
        sections.append(snowflake_section)
        exported_names.append("Snowflake")

    sections.append(_generate_schedule_section())

    for section in sections:
        lines.extend(["", "", *section])

    lines.extend(["", "", f"__all__ = {exported_names!r}", ""])
    return "\n".join(lines)


def write_generated_module(project_dir: Path, content: str) -> Path:
    """Write the generated helper module into the project's src directory."""

    output_path = project_dir / "src" / "terse_generated.py"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")
    return output_path


def _build_codegen_input(active_set: set[str], api_key: str) -> CodegenInput:
    return CodegenInput(
        attio=_safe_fetch(lambda: _fetch_attio_instances(api_key)) if "attio" in active_set else [],
        snowflake=_safe_fetch(lambda: _fetch_snowflake_instances(api_key)) if "snowflake" in active_set else [],
    )


def _safe_fetch(fetcher: Callable[[], list[T]]) -> list[T]:
    try:
        return fetcher()
    except Exception:
        return []


def _as_dict(value: object) -> dict[str, Any] | None:
    if isinstance(value, dict):
        return cast(dict[str, Any], value)
    return None


def _as_list(value: object) -> list[Any]:
    if isinstance(value, list):
        return cast(list[Any], value)
    return []


def _fetch_attio_instances(api_key: str) -> list[AttioInstanceData]:
    raw_instances = _as_list(request_json("/attio/integrations", api_key))
    instances: list[AttioInstanceData] = []

    for integration in raw_instances:
        integration_data = _as_dict(integration)
        if integration_data is None:
            continue

        integration_id = str(integration_data.get("id", ""))
        raw_objects = _safe_request_json(
            f"/attio/integrations/{quote(integration_id, safe='')}/objects",
            api_key,
        )
        objects = [
            AttioObjectData(
                api_slug=str((_as_dict(raw_object) or {}).get("api_slug", "")),
                singular_noun=str((_as_dict(raw_object) or {}).get("singular_noun", "")),
            )
            for raw_object in _as_list(raw_objects)
            if _as_dict(raw_object) is not None and str((_as_dict(raw_object) or {}).get("api_slug", ""))
        ]
        instances.append(
            AttioInstanceData(
                id=integration_id,
                display_name=str(integration_data.get("workspaceName") or integration_id),
                objects=objects,
            )
        )

    return instances


def _fetch_snowflake_instances(api_key: str) -> list[SnowflakeInstanceData]:
    raw_instances = _as_list(request_json("/snowflake/integrations", api_key))
    return [
        SnowflakeInstanceData(
            id=str((_as_dict(integration) or {}).get("id", "")),
            display_name=str(
                (_as_dict(integration) or {}).get("accountIdentifier") or (_as_dict(integration) or {}).get("id") or ""
            ),
        )
        for integration in raw_instances
        if _as_dict(integration) is not None
    ]


def _safe_request_json(path: str, api_key: str) -> object | None:
    try:
        return request_json(path, api_key)
    except Exception:
        return None


def _build_summary_lines(codegen_input: CodegenInput) -> list[str]:
    lines = [f"Attio ({instance.display_name}) — {len(instance.objects)} objects" for instance in codegen_input.attio]
    lines.extend(f"Snowflake ({instance.display_name})" for instance in codegen_input.snowflake)
    lines.append("Schedule trigger")
    return lines


def _generate_attio_section(instances: list[AttioInstanceData]) -> list[str]:
    if not instances:
        return []

    instance = instances[0]
    namespace_lines = _generate_attio_namespace(instance.objects)

    return [
        "# === Attio ===",
        "",
        *namespace_lines,
        "",
        "class Attio:",
        "    @staticmethod",
        "    def skill(*, obj: AttioObjectResource | None = None) -> SkillConfig:",
        (
            "        return SkillConfig("
            f"integration_id={instance.id!r}, "
            "integration_type='attio', "
            "config_type='attio_output', "
            "config=_compact_dict(objectSlug=obj.api_slug if obj else None)"
            ")"
        ),
    ]


def _generate_attio_namespace(objects: list[AttioObjectData]) -> list[str]:
    lines = [
        "@dataclass(frozen=True)",
        "class AttioObjectResource:",
        "    api_slug: str",
        "    name: str",
        "",
    ]

    if not objects:
        lines.append("AttioObject = SimpleNamespace()")
        return lines

    lines.append("AttioObject = SimpleNamespace(")
    used_names: set[str] = set()
    for obj in objects:
        static_name = _unique_name(_to_pascal_case(obj.singular_noun or obj.api_slug) or "Object", used_names)
        lines.append(f"    {static_name}=AttioObjectResource(api_slug={obj.api_slug!r}, name={obj.singular_noun!r}),")
    lines.append(")")
    return lines


def _generate_snowflake_section(instances: list[SnowflakeInstanceData]) -> list[str]:
    if not instances:
        return []

    instance = instances[0]
    return [
        "# === Snowflake ===",
        "",
        "class Snowflake:",
        "    @staticmethod",
        "    def skill(",
        "        *,",
        "        warehouse: str | None = None,",
        "        database_name: str | None = None,",
        "        schema_name: str | None = None,",
        "    ) -> SkillConfig:",
        (
            "        return SkillConfig("
            f"integration_id={instance.id!r}, "
            "integration_type='snowflake', "
            "config_type='snowflake_output', "
            "config=_compact_dict("
            "warehouse=warehouse, "
            "databaseName=database_name, "
            "schemaName=schema_name"
            ")"
            ")"
        ),
    ]


def _generate_schedule_section() -> list[str]:
    return [
        "# === Schedule ===",
        "",
        "class Schedule:",
        "    @staticmethod",
        "    def cron(expression: str) -> TriggerConfig:",
        (
            "        return TriggerConfig("
            "integration_id='system', "
            "integration_type='cron_job', "
            "config_type='time_trigger', "
            "config=_compact_dict(cronExpression=expression)"
            ")"
        ),
    ]


def _to_pascal_case(value: str) -> str:
    parts = re.split(r"[^0-9A-Za-z]+", value)
    normalized = "".join(part[:1].upper() + part[1:] for part in parts if part)
    if normalized[:1].isdigit():
        return f"_{normalized}"
    return normalized


def _unique_name(candidate: str, used_names: set[str]) -> str:
    if candidate not in used_names:
        used_names.add(candidate)
        return candidate

    index = 2
    while f"{candidate}{index}" in used_names:
        index += 1

    unique_name = f"{candidate}{index}"
    used_names.add(unique_name)
    return unique_name
