import { readFile, writeFile } from "node:fs/promises"
import { resolve } from "node:path"
import { fileURLToPath } from "node:url"
import openapiTS, { astToString } from "openapi-typescript"
import { format, resolveConfig } from "prettier"

const APOLLO_SPEC_URL = "https://docs.apollo.io/openapi/apollo-rest-api.json"
const OUTPUT_DIRECTORY = fileURLToPath(new URL("../../src/integrations/apollo/", import.meta.url))

const responseSelections = {
    "people-enrichment": {
        person: enrichedPersonSelection()
    },
    "bulk-people-enrichment": {
        matches: { "[]": enrichedPersonSelection() }
    },
    "organization-enrichment": {
        organization: organizationSelection()
    },
    "people-api-search": {
        people: { "[]": searchPersonSelection() },
        total_entries: {}
    },
    "organization-jobs-postings": {
        organization_job_postings: {
            "[]": {
                id: {},
                title: {},
                url: {},
                city: {},
                state: {},
                country: {},
                posted_at: {},
                last_seen_at: {}
            }
        }
    }
} as const satisfies Record<string, Selection>

const spec = await loadSpec(process.argv.slice(2))
const reducedSpec = reduceSpec(spec, responseSelections)
const typeAst = await openapiTS(reducedSpec)
const generatedTypes = `// This file was auto-generated by scripts/typeGen/apollo-io.ts. Do not edit directly.
${astToString(typeAst)}
export type OperationId = keyof operations

type JsonContent<T> = T extends { content: infer Content }
    ? Content extends { "application/json": infer Body }
        ? Body
        : never
    : never

type Responses<Id extends OperationId> = operations[Id]["responses"]

export type SuccessResponseBody<Id extends OperationId> = {
    [Status in keyof Responses<Id>]: \`${"${Status & (string | number)}"}\` extends \`2${"${string}"}\`
        ? JsonContent<Responses<Id>[Status]>
        : never
}[keyof Responses<Id>]
`

await writeGeneratedFile("apollo.generated.ts", generatedTypes)
await writeGeneratedFile("apolloSchemas.generated.ts", generateRuntimeSchemas(reducedSpec, Object.keys(responseSelections)))
console.log(`Generated ${Object.keys(responseSelections).length} Apollo response types and validators.`)

async function writeGeneratedFile(fileName: string, source: string): Promise<void> {
    const outputPath = resolve(OUTPUT_DIRECTORY, fileName)
    const prettierConfig = await resolveConfig(outputPath)
    await writeFile(outputPath, await format(source, { ...prettierConfig, filepath: outputPath }))
}

function enrichedPersonSelection(): Selection {
    return {
        id: {},
        first_name: {},
        last_name: {},
        name: {},
        title: {},
        seniority: {},
        email: {},
        email_status: {},
        linkedin_url: {},
        city: {},
        state: {},
        country: {},
        organization: organizationSummarySelection()
    }
}

function searchPersonSelection(): Selection {
    return {
        id: {},
        first_name: {},
        last_name_obfuscated: {},
        title: {},
        has_email: {},
        organization: { name: {} }
    }
}

function organizationSummarySelection(): Selection {
    return {
        id: {},
        name: {},
        website_url: {},
        primary_domain: {},
        industry: {},
        estimated_num_employees: {}
    }
}

function organizationSelection(): Selection {
    return {
        id: {},
        name: {},
        website_url: {},
        primary_domain: {},
        industry: {},
        estimated_num_employees: {},
        keywords: { "[]": {} },
        annual_revenue_printed: {},
        total_funding_printed: {},
        latest_funding_stage: {},
        founded_year: {},
        city: {},
        state: {},
        country: {},
        linkedin_url: {},
        short_description: {},
        technology_names: { "[]": {} }
    }
}

async function loadSpec(args: string[]): Promise<OpenApiDocument> {
    const specFlag = args.indexOf("--spec")
    if (specFlag >= 0) {
        const path = args[specFlag + 1]
        if (!path) throw new Error("--spec requires a file path")
        return parseSpec(await readFile(resolve(path), "utf8"), path)
    }

    const response = await fetch(APOLLO_SPEC_URL)
    if (!response.ok) throw new Error(`Failed to download Apollo OpenAPI spec: ${response.status}`)
    return parseSpec(await response.text(), APOLLO_SPEC_URL)
}

function parseSpec(source: string, sourceName: string): OpenApiDocument {
    const parsed: unknown = JSON.parse(source)
    if (!isRecord(parsed) || typeof parsed.openapi !== "string" || !isRecord(parsed.paths)) {
        throw new Error(`${sourceName} is not an OpenAPI document`)
    }
    return parsed as OpenApiDocument
}

function reduceSpec(document: OpenApiDocument, selections: Record<string, Selection>): OpenApiDocument {
    const paths: Record<string, unknown> = {}
    const found = new Set<string>()

    for (const [path, pathItem] of Object.entries(document.paths)) {
        if (!isRecord(pathItem)) continue
        for (const [method, operation] of Object.entries(pathItem)) {
            if (!isRecord(operation) || typeof operation.operationId !== "string") continue
            const selection = selections[operation.operationId]
            if (!selection) continue

            const response = successJsonResponse(operation, operation.operationId)
            paths[path] = {
                [method]: {
                    operationId: operation.operationId,
                    responses: {
                        200: {
                            description: "Success",
                            content: {
                                "application/json": {
                                    schema: projectSchema(response.schema, selection)
                                }
                            }
                        }
                    }
                }
            }
            found.add(operation.operationId)
        }
    }

    const missing = Object.keys(selections).filter(operationId => !found.has(operationId))
    if (missing.length) throw new Error(`Apollo spec is missing operations: ${missing.join(", ")}`)

    return { openapi: "3.1.0", info: { title: "Apollo API (Terse subset)", version: "1" }, paths }
}

function successJsonResponse(operation: Record<string, unknown>, operationId: string): { schema: JsonSchema } {
    const responses = expectRecord(operation.responses, `${operationId}.responses`)
    const success = expectRecord(responses["200"], `${operationId}.responses.200`)
    const content = expectRecord(success.content, `${operationId}.responses.200.content`)
    const json = expectRecord(content["application/json"], `${operationId}.responses.200.content.application/json`)
    return { schema: expectRecord(json.schema, `${operationId}.responses.200.content.application/json.schema`) }
}

function projectSchema(schema: JsonSchema, selection: Selection): JsonSchema {
    if ("[]" in selection) {
        const items = expectRecord(schema.items, "array schema items")
        return { ...schemaKeywords(schema), type: "array", items: projectSchema(items, selection["[]"] ?? {}) }
    }

    const selectedProperties = Object.entries(selection)
    if (selectedProperties.length) {
        const properties = expectRecord(schema.properties, "object schema properties")
        const projectedProperties = Object.fromEntries(
            selectedProperties.map(([name, childSelection]) => {
                const child = properties[name]
                if (!isRecord(child)) throw new Error(`Apollo response schema no longer has selected field ${name}`)
                return [name, projectSchema(child, childSelection)]
            })
        )
        const required = Array.isArray(schema.required) ? schema.required.filter(name => typeof name === "string" && name in selection) : []
        return {
            ...schemaKeywords(schema),
            type: "object",
            properties: projectedProperties,
            ...(required.length ? { required } : {}),
            additionalProperties: true
        }
    }

    return schemaKeywords(schema)
}

function schemaKeywords(schema: JsonSchema): JsonSchema {
    const keep = ["type", "enum", "const", "format", "pattern", "minimum", "maximum", "minLength", "maxLength", "nullable"]
    return Object.fromEntries(keep.flatMap(key => (key in schema ? [[key, schema[key]]] : [])))
}

function generateRuntimeSchemas(document: OpenApiDocument, operationIds: string[]): string {
    const schemas = operationIds.map(operationId => {
        const operation = findOperation(document, operationId)
        const responseSchema = successJsonResponse(operation, operationId).schema
        const exportName = `${operationId.replace(/-([a-z])/g, (_, letter: string) => letter.toUpperCase()).replace(/-/g, "")}ResponseSchema`
        return `export const ${exportName} = z.fromJSONSchema(${JSON.stringify(responseSchema, null, 4)} as unknown as Parameters<typeof z.fromJSONSchema>[0]) as z.ZodType<SuccessResponseBody<${JSON.stringify(operationId)}>>`
    })

    return `// This file was auto-generated by scripts/typeGen/apollo-io.ts. Do not edit directly.\nimport { z } from "zod"\nimport type { SuccessResponseBody } from "./apollo.generated.js"\n\n${schemas.join("\n\n")}\n`
}

function findOperation(document: OpenApiDocument, operationId: string): Record<string, unknown> {
    for (const pathItem of Object.values(document.paths)) {
        if (!isRecord(pathItem)) continue
        for (const operation of Object.values(pathItem)) {
            if (isRecord(operation) && operation.operationId === operationId) return operation
        }
    }
    throw new Error(`Reduced spec is missing ${operationId}`)
}

function expectRecord(value: unknown, label: string): Record<string, unknown> {
    if (!isRecord(value)) throw new Error(`Expected ${label} to be an object`)
    return value
}

function isRecord(value: unknown): value is Record<string, unknown> {
    return typeof value === "object" && value !== null && !Array.isArray(value)
}

type JsonSchema = Record<string, unknown>
type Selection = { readonly [property: string]: Selection | undefined }
interface OpenApiDocument extends Record<string, unknown> {
    openapi: string
    paths: Record<string, unknown>
}
