[tool.bumpversion]
current_version = "0.1.4"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor}.{patch}"]
allow_dirty = true
commit = false
tag = false

[[tool.bumpversion.files]]
filename = "packages/terse-python-sdk/pyproject.toml"
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'

[[tool.bumpversion.files]]
filename = "packages/terse-python-sdk/src/terse_sdk/__init__.py"
search = '__version__ = "{current_version}"'
replace = '__version__ = "{new_version}"'

[[tool.bumpversion.files]]
filename = "packages/terse-python-cli/pyproject.toml"
search = '"terse-sdk~={current_version}"'
replace = '"terse-sdk~={new_version}"'

[[tool.bumpversion.files]]
filename = "packages/terse-python-cli/tests/test_init_and_generate.py"
search = '"SDK_DEPENDENCY": "terse-sdk~={current_version}"'
replace = '"SDK_DEPENDENCY": "terse-sdk~={new_version}"'

[[tool.bumpversion.files]]
filename = "packages/terse-python-cli/src/terse_cli/_project.py"
search = 'version = _installed_version("terse-sdk") or "{current_version}"'
replace = 'version = _installed_version("terse-sdk") or "{new_version}"'
