[tool.bumpversion]
current_version = "0.1.10"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor}.{patch}"]
allow_dirty = true
commit = false
tag = false

[[tool.bumpversion.files]]
filename = "packages/terse-python-sdk/pyproject.toml"
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'

[[tool.bumpversion.files]]
filename = "packages/terse-python-sdk/src/terse_sdk/__init__.py"
search = '__version__ = "{current_version}"'
replace = '__version__ = "{new_version}"'

[[tool.bumpversion.files]]
filename = "packages/terse-cli/src/providers/python/PythonProvider.ts"
search = 'const PYTHON_SDK_DEPENDENCY = "terse-sdk~={current_version}"'
replace = 'const PYTHON_SDK_DEPENDENCY = "terse-sdk~={new_version}"'
