// This file was auto-generated by scripts/typeGen/apollo-io.ts. Do not edit directly.
import { z } from "zod"

import type { SuccessResponseBody } from "./apollo.generated.js"

export const peopleEnrichmentResponseSchema = z.fromJSONSchema({
    type: "object",
    properties: {
        person: {
            type: "object",
            properties: {
                id: {
                    type: "string"
                },
                first_name: {
                    type: "string"
                },
                last_name: {
                    type: "string"
                },
                name: {
                    type: "string"
                },
                title: {
                    type: "string"
                },
                seniority: {
                    type: "string"
                },
                email: {
                    type: "string"
                },
                email_status: {
                    type: "string"
                },
                linkedin_url: {
                    type: "string"
                },
                city: {
                    type: "string"
                },
                state: {
                    type: "string"
                },
                country: {
                    type: "string"
                },
                organization: {
                    type: "object",
                    properties: {
                        id: {
                            type: "string"
                        },
                        name: {
                            type: "string"
                        },
                        website_url: {
                            type: "string"
                        },
                        primary_domain: {
                            type: "string"
                        },
                        industry: {
                            type: "string"
                        },
                        estimated_num_employees: {
                            type: "integer"
                        }
                    },
                    additionalProperties: true
                }
            },
            additionalProperties: true
        }
    },
    additionalProperties: true
} as unknown as Parameters<typeof z.fromJSONSchema>[0]) as z.ZodType<SuccessResponseBody<"people-enrichment">>

export const bulkPeopleEnrichmentResponseSchema = z.fromJSONSchema({
    type: "object",
    properties: {
        matches: {
            type: "array",
            items: {
                type: "object",
                properties: {
                    id: {
                        type: "string"
                    },
                    first_name: {
                        type: "string"
                    },
                    last_name: {
                        type: "string"
                    },
                    name: {
                        type: "string"
                    },
                    title: {
                        type: "string"
                    },
                    seniority: {
                        type: "string"
                    },
                    email: {
                        type: "string"
                    },
                    email_status: {
                        type: "string"
                    },
                    linkedin_url: {
                        type: "string"
                    },
                    city: {
                        type: "string"
                    },
                    state: {
                        type: "string"
                    },
                    country: {
                        type: "string"
                    },
                    organization: {
                        type: "object",
                        properties: {
                            id: {
                                type: "string"
                            },
                            name: {
                                type: "string"
                            },
                            website_url: {
                                type: "string"
                            },
                            primary_domain: {
                                type: "string"
                            },
                            industry: {
                                type: "string"
                            },
                            estimated_num_employees: {
                                type: "integer"
                            }
                        },
                        additionalProperties: true
                    }
                },
                additionalProperties: true
            }
        }
    },
    additionalProperties: true
} as unknown as Parameters<typeof z.fromJSONSchema>[0]) as z.ZodType<SuccessResponseBody<"bulk-people-enrichment">>

export const organizationEnrichmentResponseSchema = z.fromJSONSchema({
    type: "object",
    properties: {
        organization: {
            type: "object",
            properties: {
                id: {
                    type: "string"
                },
                name: {
                    type: "string"
                },
                website_url: {
                    type: "string"
                },
                primary_domain: {
                    type: "string"
                },
                industry: {
                    type: "string"
                },
                estimated_num_employees: {
                    type: "integer"
                },
                keywords: {
                    type: "array",
                    items: {
                        type: "string"
                    }
                },
                annual_revenue_printed: {
                    type: "string"
                },
                total_funding_printed: {
                    type: "string"
                },
                latest_funding_stage: {
                    type: "string"
                },
                founded_year: {
                    type: "integer"
                },
                city: {
                    type: "string"
                },
                state: {
                    type: "string"
                },
                country: {
                    type: "string"
                },
                linkedin_url: {
                    type: "string"
                },
                short_description: {
                    type: "string"
                },
                technology_names: {
                    type: "array",
                    items: {
                        type: "string"
                    }
                }
            },
            additionalProperties: true
        }
    },
    additionalProperties: true
} as unknown as Parameters<typeof z.fromJSONSchema>[0]) as z.ZodType<SuccessResponseBody<"organization-enrichment">>

export const peopleApiSearchResponseSchema = z.fromJSONSchema({
    type: "object",
    properties: {
        people: {
            type: "array",
            items: {
                type: "object",
                properties: {
                    id: {
                        type: "string"
                    },
                    first_name: {
                        type: "string"
                    },
                    last_name_obfuscated: {
                        type: "string"
                    },
                    title: {
                        type: ["string", "null"]
                    },
                    has_email: {
                        type: "boolean"
                    },
                    organization: {
                        type: "object",
                        properties: {
                            name: {
                                type: "string"
                            }
                        },
                        additionalProperties: true
                    }
                },
                additionalProperties: true
            }
        },
        total_entries: {
            type: "integer"
        }
    },
    additionalProperties: true
} as unknown as Parameters<typeof z.fromJSONSchema>[0]) as z.ZodType<SuccessResponseBody<"people-api-search">>

export const organizationJobsPostingsResponseSchema = z.fromJSONSchema({
    type: "object",
    properties: {
        organization_job_postings: {
            type: "array",
            items: {
                type: "object",
                properties: {
                    id: {
                        type: "string"
                    },
                    title: {
                        type: "string"
                    },
                    url: {
                        type: "string"
                    },
                    city: {},
                    state: {},
                    country: {
                        type: "string"
                    },
                    posted_at: {
                        type: "string"
                    },
                    last_seen_at: {
                        type: "string"
                    }
                },
                additionalProperties: true
            }
        }
    },
    additionalProperties: true
} as unknown as Parameters<typeof z.fromJSONSchema>[0]) as z.ZodType<SuccessResponseBody<"organization-jobs-postings">>
