// This file was auto-generated by scripts/typeGen/apollo-io.ts. Do not edit directly.
export interface paths {
    "/people/match": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        post: operations["people-enrichment"]
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/people/bulk_match": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        post: operations["bulk-people-enrichment"]
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/organizations/enrich": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get: operations["organization-enrichment"]
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/mixed_people/api_search": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        post: operations["people-api-search"]
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/organizations/{organization_id}/job_postings": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get: operations["organization-jobs-postings"]
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
}
export type webhooks = Record<string, never>
export interface components {
    schemas: never
    responses: never
    parameters: never
    requestBodies: never
    headers: never
    pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
    "people-enrichment": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": {
                        person?: {
                            id?: string
                            first_name?: string
                            last_name?: string
                            name?: string
                            title?: string
                            seniority?: string
                            email?: string
                            email_status?: string
                            linkedin_url?: string
                            city?: string
                            state?: string
                            country?: string
                            organization?: {
                                id?: string
                                name?: string
                                website_url?: string
                                primary_domain?: string
                                industry?: string
                                estimated_num_employees?: number
                            } & {
                                [key: string]: unknown
                            }
                        } & {
                            [key: string]: unknown
                        }
                    } & {
                        [key: string]: unknown
                    }
                }
            }
        }
    }
    "bulk-people-enrichment": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": {
                        matches?: ({
                            id?: string
                            first_name?: string
                            last_name?: string
                            name?: string
                            title?: string
                            seniority?: string
                            email?: string
                            email_status?: string
                            linkedin_url?: string
                            city?: string
                            state?: string
                            country?: string
                            organization?: {
                                id?: string
                                name?: string
                                website_url?: string
                                primary_domain?: string
                                industry?: string
                                estimated_num_employees?: number
                            } & {
                                [key: string]: unknown
                            }
                        } & {
                            [key: string]: unknown
                        })[]
                    } & {
                        [key: string]: unknown
                    }
                }
            }
        }
    }
    "organization-enrichment": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": {
                        organization?: {
                            id?: string
                            name?: string
                            website_url?: string
                            primary_domain?: string
                            industry?: string
                            estimated_num_employees?: number
                            keywords?: string[]
                            annual_revenue_printed?: string
                            total_funding_printed?: string
                            latest_funding_stage?: string
                            founded_year?: number
                            city?: string
                            state?: string
                            country?: string
                            linkedin_url?: string
                            short_description?: string
                            technology_names?: string[]
                        } & {
                            [key: string]: unknown
                        }
                    } & {
                        [key: string]: unknown
                    }
                }
            }
        }
    }
    "people-api-search": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": {
                        people?: ({
                            id?: string
                            first_name?: string
                            last_name_obfuscated?: string
                            title?: string | null
                            has_email?: boolean
                            organization?: {
                                name?: string
                            } & {
                                [key: string]: unknown
                            }
                        } & {
                            [key: string]: unknown
                        })[]
                        total_entries?: number
                    } & {
                        [key: string]: unknown
                    }
                }
            }
        }
    }
    "organization-jobs-postings": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": {
                        organization_job_postings?: ({
                            id?: string
                            title?: string
                            url?: string
                            city?: unknown
                            state?: unknown
                            country?: string
                            posted_at?: string
                            last_seen_at?: string
                        } & {
                            [key: string]: unknown
                        })[]
                    } & {
                        [key: string]: unknown
                    }
                }
            }
        }
    }
}

export type OperationId = keyof operations

type JsonContent<T> = T extends { content: infer Content } ? (Content extends { "application/json": infer Body } ? Body : never) : never

type Responses<Id extends OperationId> = operations[Id]["responses"]

export type SuccessResponseBody<Id extends OperationId> = {
    [Status in keyof Responses<Id>]: `${Status & (string | number)}` extends `2${string}` ? JsonContent<Responses<Id>[Status]> : never
}[keyof Responses<Id>]
