export type StructuredSearchOptions = {
  teamIds?: string[];
  assigneeEmails?: string[];
  createdByEmails?: string[];
  stateIds?: string[];
  priority?: number[];
  labels?: string[];
  projects?: string[];
  dueDateRange?: { from?: Date; to?: Date };
  createdDateRange?: { from?: Date; to?: Date };
  updatedDateRange?: { from?: Date; to?: Date };
  sortBy?: "createdAt" | "updatedAt";
  sortDirection?: "asc" | "desc";
  limit?: number;
  includeArchived?: boolean;
  includeSubIssues?: boolean;
  includeComments?: boolean;
  includeAttachments?: boolean;
  includeRelations?: boolean;
};
