import Handlebars from "handlebars"
import fs from "node:fs"
import path from "node:path"

import type { GeneratedFile } from "../LanguageProvider.js"
import { getTemplatesRoot, readTemplateFile } from "../templateUtils.js"

import { type TemplateContext, escapeString } from "./prepareCodegenData.js"

const GENERATED_DIR = "terse.generated"

const LEAF_BANNER = [
    "// Auto-generated by `terse generate` — do not edit manually.",
    '// Part of the terse.generated bundle: import symbols from "./terse.generated" (the root file), which re-exports everything here.'
].join("\n")

export function renderGeneratedFiles(context: TemplateContext): GeneratedFile[] {
    const handlebars = getHandlebars()
    const leaves = buildLeafSpecs(context).map(spec => ({ ...spec, body: renderBody(handlebars, `files/${spec.templateFile}.hbs`, context) }))
    const declarations = new Map(leaves.map(leaf => [leaf.fileName, extractDeclarations(leaf.body)]))
    const assembled = leaves.map(leaf => assembleLeaf(leaf, context, leaves, declarations))
    const root = assembleRoot(handlebars, context, assembled)
    return [root, ...assembled.map(leaf => ({ fileName: `${GENERATED_DIR}/${leaf.fileName}`, code: leaf.code }))]
}

function buildLeafSpecs(context: TemplateContext): LeafSpec[] {
    const specs: LeafSpec[] = []
    if (context.commonToolDeclarations.length > 0) {
        specs.push({ fileName: "common.ts", templateFile: "common", kind: "common" })
    }

    const integrations: Array<{ contextKey: keyof TemplateContext; name: string; hasTriggers: boolean; hasSchemas?: boolean }> = [
        { contextKey: "github", name: "github", hasTriggers: true },
        { contextKey: "gmail", name: "gmail", hasTriggers: true },
        { contextKey: "slack", name: "slack", hasTriggers: true },
        { contextKey: "linear", name: "linear", hasTriggers: true },
        { contextKey: "notion", name: "notion", hasTriggers: false },
        { contextKey: "posthog", name: "posthog", hasTriggers: false },
        { contextKey: "datadog", name: "datadog", hasTriggers: false },
        { contextKey: "launchdarkly", name: "launchdarkly", hasTriggers: false },
        { contextKey: "workos", name: "workos", hasTriggers: true },
        { contextKey: "attio", name: "attio", hasTriggers: true, hasSchemas: true },
        { contextKey: "snowflake", name: "snowflake", hasTriggers: false },
        { contextKey: "heyreach", name: "heyreach", hasTriggers: true }
    ]

    for (const integration of integrations) {
        if (!context[integration.contextKey]) continue
        if (integration.hasSchemas) {
            specs.push({ fileName: `${integration.name}.schemas.ts`, templateFile: `${integration.name}.schemas`, kind: "schemas", integration: integration.name })
        }
        specs.push({ fileName: `${integration.name}.tools.ts`, templateFile: `${integration.name}.tools`, kind: "tools", integration: integration.name })
        if (integration.hasTriggers) {
            specs.push({ fileName: `${integration.name}.triggers.ts`, templateFile: `${integration.name}.triggers`, kind: "triggers", integration: integration.name })
        }
    }
    return specs
}

function assembleLeaf(leaf: RenderedLeaf, context: TemplateContext, allLeaves: RenderedLeaf[], declarations: Map<string, DeclaredName[]>): AssembledLeaf {
    const ownNames = new Set((declarations.get(leaf.fileName) ?? []).map(declaration => declaration.name))
    const sdkImportLines = buildSdkImportLines(leaf.body, context.imports, ownNames)
    const siblingImportLines = allLeaves
        .filter(sibling => KIND_TIER[sibling.kind] < KIND_TIER[leaf.kind])
        .flatMap(sibling => buildSiblingImportLines(leaf.body, ownNames, declarations.get(sibling.fileName) ?? [], `./${moduleName(sibling.fileName)}.js`))
    const importBlock = [...sdkImportLines, ...siblingImportLines].join("\n")
    const code = postprocess([LEAF_BANNER, importBlock, leaf.body].filter(Boolean).join("\n\n"))
    return { ...leaf, code, exports: (declarations.get(leaf.fileName) ?? []).filter(declaration => declaration.exported) }
}

function assembleRoot(handlebars: typeof Handlebars, context: TemplateContext, leaves: AssembledLeaf[]): GeneratedFile {
    const body = renderBody(handlebars, "root.hbs", context)
    const ownNames = new Set(extractDeclarations(body).map(declaration => declaration.name))
    const sdkImportLines = buildSdkImportLines(body, [...new Set([...context.imports, "TerseAgent"])].sort(), ownNames)
    const siblingImportLines = leaves.flatMap(leaf => buildSiblingImportLines(body, ownNames, leaf.exports, `./${GENERATED_DIR}/${moduleName(leaf.fileName)}.js`))
    const reexportLines = leaves.map(leaf => `export * from "./${GENERATED_DIR}/${moduleName(leaf.fileName)}.js"`)
    const header = buildRootHeader(context, leaves)
    const code = postprocess([header, [...sdkImportLines, ...siblingImportLines].join("\n"), reexportLines.join("\n"), body].filter(Boolean).join("\n\n"))
    return { fileName: "terse.generated.ts", code }
}

function buildRootHeader(context: TemplateContext, leaves: AssembledLeaf[]): string {
    const lines: string[] = ["// Auto-generated by `terse generate` — do not edit manually.", "// Re-run `terse generate` to update."]
    if (context.availableIntegrations) {
        lines.push("//")
        lines.push(`// The integrations currently available in Terse: ${context.availableIntegrations}.`)
        lines.push("// Connect one with `terse integrate connect <type>`; list its tools with `terse integrate tool <type> --json`.")
    }
    lines.push("//")
    lines.push("// This file is the only import surface — everything generated is re-exported here:")
    lines.push('//   import { Triggers, Skills, toolbox, ... } from "./terse.generated"')
    lines.push("// The terse.generated/ folder holds the per-integration declarations. Read only the files you need:")
    lines.push("//   <integration>.triggers.ts — trigger factories (Triggers.<integration>.*) and their payload types")
    lines.push("//   <integration>.tools.ts    — typed tool methods (toolbox.<integration>.*), their Params/Result types, pinned resources, and skills")
    if (leaves.some(leaf => leaf.kind === "schemas")) {
        lines.push("//   <integration>.schemas.ts  — workspace-specific value/record types (Attio objects and lists)")
    }
    lines.push("// Built-in triggers (schedule, webhook, webMonitor), Skills and the toolbox aggregate live in this file, below.")
    lines.push("")
    lines.push(readTemplateFile("typescript/codegen/sdk-primitives.hbs").trimEnd())

    const indexLines = leaves.flatMap(leaf => buildIndexLines(leaf, context))
    if (indexLines.length > 0) {
        lines.push("//")
        lines.push("// Index of the generated files. Line numbers are exact as of the last `terse generate`;")
        lines.push("// if a formatter has touched a file since, search for the symbol name instead.")
        lines.push("//")
        lines.push(...indexLines)
    }
    return lines.join("\n")
}

function buildIndexLines(leaf: AssembledLeaf, context: TemplateContext): string[] {
    const rows = collectIndexRows(leaf, context)
    if (rows.length === 0) return []
    const width = Math.max(...rows.map(row => String(row.line).length))
    return [`// ${GENERATED_DIR}/${leaf.fileName}`, ...rows.map(row => `//   L${String(row.line).padEnd(width)}  ${row.label}`)]
}

function collectIndexRows(leaf: AssembledLeaf, context: TemplateContext): IndexRow[] {
    const lines = leaf.code.split("\n")
    const rows: IndexRow[] = []
    const declarationLineByName = new Map<string, number>()
    lines.forEach((line, index) => {
        const declaration = line.match(DECLARATION_PATTERN)
        if (declaration?.[1]) declarationLineByName.set(declaration[3], index + 1)
    })

    const typeNameToToolboxKey = new Map(context.toolboxEntries.map(entry => [entry.typeName, entry.key]))
    let openBlock: { type: "tools"; key: string } | { type: "triggers"; key: string } | undefined

    lines.forEach((line, index) => {
        const lineNumber = index + 1

        if (openBlock) {
            if (line === "}") {
                openBlock = undefined
                return
            }
            const method = line.match(/^ {4}(\w+)[(<]/)
            if (!method) return
            if (openBlock.type === "tools") {
                const paramsType = line.match(/params: (\w+)/)?.[1]
                const paramsLine = paramsType ? declarationLineByName.get(paramsType) : undefined
                const paramsSuffix = paramsLine ? `  (params L${paramsLine})` : ""
                rows.push({ line: lineNumber, label: `toolbox.${openBlock.key}.${method[1]}()${paramsSuffix}` })
            } else {
                rows.push({ line: lineNumber, label: `Triggers.${openBlock.key}.${method[1]}()` })
            }
            return
        }

        const toolsBlock = line.match(/^export type (\w+) = \{$/)
        if (toolsBlock && typeNameToToolboxKey.has(toolsBlock[1])) {
            openBlock = { type: "tools", key: typeNameToToolboxKey.get(toolsBlock[1])! }
            return
        }
        const triggersBlock = line.match(/^export const (\w+)Triggers = \{$/)
        if (triggersBlock) {
            openBlock = { type: "triggers", key: triggersBlock[1] }
            return
        }

        const declaration = line.match(DECLARATION_PATTERN)
        if (!declaration || !declaration[1]) return
        const [, , keyword, name] = declaration
        if (keyword === "class") rows.push({ line: lineNumber, label: `class ${name}` })
        else if (keyword === "function") rows.push({ line: lineNumber, label: `function ${name}()` })
        else if ((keyword === "type" || keyword === "interface") && indexableTypeName(leaf.kind, name)) rows.push({ line: lineNumber, label: `type ${name}` })
    })
    return rows
}

function indexableTypeName(kind: LeafKind, name: string): boolean {
    switch (kind) {
        case "common":
            return true
        case "tools":
            return !/(Params|Result|GeneratedTools)$/.test(name)
        case "schemas":
            return /(RecordValues|InputValues|EntryValues|EntryRecordValues|ValuesFor|FilterFor)$/.test(name) || name === "GeneratedAttioObject" || name === "GeneratedAttioList"
        case "triggers":
            return false
        default:
            throw kind satisfies never
    }
}

function buildSdkImportLines(body: string, candidates: readonly string[], ownNames: ReadonlySet<string>): string[] {
    const used = candidates.filter(name => !ownNames.has(name) && referencesName(body, name))
    if (used.length === 0) return []
    if (used.length > 3) {
        return ["import {", ...used.map(name => `    ${name},`), '} from "terse-sdk"']
    }
    return [`import { ${used.join(", ")} } from "terse-sdk"`]
}

function buildSiblingImportLines(body: string, ownNames: ReadonlySet<string>, siblingDeclarations: readonly DeclaredName[], specifier: string): string[] {
    const used = siblingDeclarations.filter(declaration => declaration.exported && !ownNames.has(declaration.name) && referencesName(body, declaration.name))
    const values = used.filter(declaration => declaration.kind === "value").map(declaration => declaration.name)
    const types = used.filter(declaration => declaration.kind === "type").map(declaration => declaration.name)
    const lines: string[] = []
    if (values.length > 0) lines.push(`import { ${values.join(", ")} } from "${specifier}"`)
    if (types.length > 0) lines.push(`import type { ${types.join(", ")} } from "${specifier}"`)
    return lines
}

const DECLARATION_PATTERN = /^(export )?(?:declare )?(?:abstract )?(type|interface|class|function|const|enum)\s+(\w+)/

function extractDeclarations(body: string): DeclaredName[] {
    const declarations: DeclaredName[] = []
    const seen = new Set<string>()
    for (const line of body.split("\n")) {
        const match = line.match(DECLARATION_PATTERN)
        if (!match || seen.has(match[3])) continue
        seen.add(match[3])
        declarations.push({ name: match[3], kind: match[2] === "type" || match[2] === "interface" ? "type" : "value", exported: Boolean(match[1]) })
    }
    return declarations
}

function referencesName(body: string, name: string): boolean {
    return new RegExp(`\\b${name}\\b`).test(body)
}

function moduleName(fileName: string): string {
    return fileName.replace(/\.ts$/, "")
}

function postprocess(code: string): string {
    return code.replace(/\n{3,}/g, "\n\n").replace(/\n+$/, "")
}

function renderBody(handlebars: typeof Handlebars, templatePath: string, context: TemplateContext): string {
    return getCompiledTemplate(handlebars, templatePath)(context)
}

function getHandlebars(): typeof Handlebars {
    const handlebars = Handlebars.create()

    handlebars.registerHelper("sectionHeader", (name: string) => {
        const dashes = "─".repeat(Math.max(1, 58 - name.length))
        return `// ── ${name} ${dashes}`
    })
    handlebars.registerHelper("escape", (value: unknown) => escapeString(String(value ?? "")))
    handlebars.registerHelper("eq", (left: unknown, right: unknown) => left === right)
    handlebars.registerHelper("joinPipe", (values: unknown) => (Array.isArray(values) ? values.join(" | ") : ""))

    const partialsDir = path.join(getTemplatesRoot(), "typescript", "codegen", "partials")
    for (const entry of fs.readdirSync(partialsDir).sort()) {
        if (!entry.endsWith(".hbs")) continue
        const partialName = path.basename(entry, ".hbs")
        handlebars.registerPartial(partialName, fs.readFileSync(path.join(partialsDir, entry), "utf-8"))
    }

    return handlebars
}

const templateCache = new Map<string, Handlebars.TemplateDelegate<TemplateContext>>()

function getCompiledTemplate(handlebars: typeof Handlebars, templatePath: string): Handlebars.TemplateDelegate<TemplateContext> {
    let template = templateCache.get(templatePath)
    if (!template) {
        template = handlebars.compile<TemplateContext>(readTemplateFile(`typescript/codegen/${templatePath}`), { noEscape: true })
        templateCache.set(templatePath, template)
    }
    return template
}

type LeafKind = "common" | "schemas" | "tools" | "triggers"

const KIND_TIER: Record<LeafKind, number> = { common: 0, schemas: 1, tools: 2, triggers: 3 }

interface LeafSpec {
    fileName: string
    templateFile: string
    kind: LeafKind
    integration?: string
}

interface RenderedLeaf extends LeafSpec {
    body: string
}

interface AssembledLeaf extends RenderedLeaf {
    code: string
    exports: DeclaredName[]
}

interface DeclaredName {
    name: string
    kind: "type" | "value"
    exported: boolean
}

interface IndexRow {
    line: number
    label: string
}
