import { IntegrationType } from "terse-types"

import type { GeneratedFile } from "../LanguageProvider.js"
import { readTemplateFile } from "../templateUtils.js"

import type { LeafFile, LeafKind, ModuleOutput, ToolboxEntryContext } from "./modules/IntegrationModule.js"
import { ModuleTemplateRenderer } from "./modules/templateRenderer.js"

const GENERATED_DIR = "terse.generated"

// The aggregate blocks in the root preserve the hand-curated ordering the file always had;
// module contributions are data, this is the one place that decides their sequence.
const TRIGGERS_AGGREGATE_ORDER: readonly IntegrationType[] = [
    IntegrationType.SLACK,
    IntegrationType.GITHUB,
    IntegrationType.LINEAR,
    IntegrationType.GMAIL,
    IntegrationType.HEY_REACH,
    IntegrationType.ATTIO,
    IntegrationType.WORKOS,
    IntegrationType.TERSE
]

const SKILLS_AGGREGATE_ORDER: readonly IntegrationType[] = [
    IntegrationType.SLACK,
    IntegrationType.GITHUB,
    IntegrationType.LINEAR,
    IntegrationType.GMAIL,
    IntegrationType.NOTION,
    IntegrationType.POSTHOG,
    IntegrationType.DATADOG,
    IntegrationType.LAUNCHDARKLY,
    IntegrationType.WORKOS,
    IntegrationType.ATTIO,
    IntegrationType.SNOWFLAKE,
    IntegrationType.RESEND,
    IntegrationType.TERSE
]

const LEAF_BANNER = [
    "// Auto-generated by `terse generate` — do not edit manually.",
    '// Part of the terse.generated bundle: import symbols from "./terse.generated" (the root file), which re-exports everything here.'
].join("\n")

export function assembleGeneratedFiles(input: AssembleGeneratedFilesInput): GeneratedFile[] {
    const renderer = ModuleTemplateRenderer.getInstance()
    const outputs = input.moduleOutputs.filter(output => output.leafFiles.length > 0)

    const imports = collectSdkImportCandidates(outputs)
    const leaves: LeafFile[] = [...buildCommonLeaf(renderer, input.commonToolDeclarations), ...outputs.flatMap(output => output.leafFiles)]
    const declarations = new Map(leaves.map(leaf => [leaf.fileName, extractDeclarations(leaf.body)]))
    const assembled = leaves.map(leaf => assembleLeaf(leaf, imports, leaves, declarations))

    const toolboxEntries = outputs.flatMap(output => output.toolboxEntries).sort((a, b) => a.key.localeCompare(b.key))
    const root = assembleRoot(renderer, input, outputs, imports, toolboxEntries, assembled)
    return [root, ...assembled.map(leaf => ({ fileName: `${GENERATED_DIR}/${leaf.fileName}`, code: leaf.code }))]
}

function collectSdkImportCandidates(outputs: readonly ModuleOutput[]): string[] {
    const candidates = new Set(outputs.flatMap(output => [...output.sdkImports]))
    const declaredNames = new Set(outputs.flatMap(output => [...output.triggerDeclaredNames]))
    declaredNames.forEach(name => candidates.delete(name))
    if (declaredNames.size > 0) candidates.add("SDKTrigger")
    outputs.flatMap(output => [...output.triggerExtraImports]).forEach(name => candidates.add(name))
    return [...candidates].sort()
}

function buildCommonLeaf(renderer: ModuleTemplateRenderer, commonToolDeclarations: readonly string[]): LeafFile[] {
    if (commonToolDeclarations.length === 0) return []
    return [{ fileName: "common.ts", kind: "common", body: renderer.renderCodegenTemplate("common.hbs", { commonToolDeclarations }) }]
}

function aggregateLines(outputs: readonly ModuleOutput[], order: readonly IntegrationType[], linesOf: (output: ModuleOutput) => readonly string[]): string[] {
    const outputByType = new Map(outputs.map(output => [output.integration, output]))
    return order.flatMap(type => {
        const output = outputByType.get(type)
        return output ? [...linesOf(output)] : []
    })
}

function assembleLeaf(leaf: LeafFile, importCandidates: readonly string[], allLeaves: LeafFile[], declarations: Map<string, DeclaredName[]>): AssembledLeaf {
    const ownNames = new Set((declarations.get(leaf.fileName) ?? []).map(declaration => declaration.name))
    const sdkImportLines = buildSdkImportLines(leaf.body, importCandidates, ownNames)
    const siblingImportLines = allLeaves
        .filter(sibling => KIND_TIER[sibling.kind] < KIND_TIER[leaf.kind])
        .flatMap(sibling => buildSiblingImportLines(leaf.body, ownNames, declarations.get(sibling.fileName) ?? [], `./${moduleName(sibling.fileName)}.js`))
    const importBlock = [...sdkImportLines, ...siblingImportLines].join("\n")
    const code = postprocess([LEAF_BANNER, importBlock, leaf.body].filter(Boolean).join("\n\n"))
    return { ...leaf, code, exports: (declarations.get(leaf.fileName) ?? []).filter(declaration => declaration.exported) }
}

function assembleRoot(
    renderer: ModuleTemplateRenderer,
    input: AssembleGeneratedFilesInput,
    outputs: readonly ModuleOutput[],
    importCandidates: readonly string[],
    toolboxEntries: readonly ToolboxEntryContext[],
    leaves: AssembledLeaf[]
): GeneratedFile {
    const body = renderer.renderCodegenTemplate("root.hbs", {
        toolboxEntries,
        triggersAggregateLines: aggregateLines(outputs, TRIGGERS_AGGREGATE_ORDER, output => output.triggersAggregateLines),
        skillsAggregateLines: aggregateLines(outputs, SKILLS_AGGREGATE_ORDER, output => output.skillsAggregateLines)
    })
    const ownNames = new Set(extractDeclarations(body).map(declaration => declaration.name))
    const sdkImportLines = buildSdkImportLines(body, [...new Set([...importCandidates, "TerseAgent"])].sort(), ownNames)
    const siblingImportLines = leaves.flatMap(leaf => buildSiblingImportLines(body, ownNames, leaf.exports, `./${GENERATED_DIR}/${moduleName(leaf.fileName)}.js`))
    const reexportLines = leaves.map(leaf => `export * from "./${GENERATED_DIR}/${moduleName(leaf.fileName)}.js"`)
    const header = buildRootHeader(input.availableIntegrations, toolboxEntries, leaves)
    const code = postprocess([header, [...sdkImportLines, ...siblingImportLines].join("\n"), reexportLines.join("\n"), body].filter(Boolean).join("\n\n"))
    return { fileName: "terse.generated.ts", code }
}

function buildRootHeader(availableIntegrations: string | undefined, toolboxEntries: readonly ToolboxEntryContext[], leaves: AssembledLeaf[]): string {
    const lines: string[] = ["// Auto-generated by `terse generate` — do not edit manually.", "// Re-run `terse generate` to update."]
    if (availableIntegrations) {
        lines.push("//")
        lines.push(`// The integrations currently available in Terse: ${availableIntegrations}.`)
        lines.push("// Connect one with `terse integrate connect <type>`; list its tools with `terse integrate tool <type> --json`.")
    }
    lines.push("//")
    lines.push("// This file is the only import surface — everything generated is re-exported here:")
    lines.push('//   import { Triggers, Skills, toolbox, ... } from "./terse.generated"')
    lines.push("// The terse.generated/ folder holds the per-integration declarations. Read only the files you need:")
    lines.push("//   <integration>.triggers.ts — trigger factories (Triggers.<integration>.*) and their payload types")
    lines.push("//   <integration>.tools.ts    — typed tool methods (toolbox.<integration>.*), their Params/Result types, pinned resources, and skills")
    if (leaves.some(leaf => leaf.kind === "schemas")) {
        lines.push("//   <integration>.schemas.ts  — workspace-specific value/record types (Attio objects and lists)")
    }
    lines.push("//   terse.triggers.ts / terse.tools.ts — built-in triggers (schedule, webhook, webMonitor), built-in tools, and the web/imageEdit/memory skills")
    lines.push("// Below the index, this file only composes: the Triggers/Skills/toolbox aggregates re-export what the folder defines.")
    lines.push("")
    lines.push(readTemplateFile("typescript/codegen/sdk-primitives.hbs").trimEnd())

    const indexLines = leaves.flatMap(leaf => buildIndexLines(leaf, toolboxEntries))
    if (indexLines.length > 0) {
        lines.push("//")
        lines.push("// Index of the generated files. Line numbers are exact as of the last `terse generate`;")
        lines.push("// if a formatter has touched a file since, search for the symbol name instead.")
        lines.push("//")
        lines.push(...indexLines)
    }
    return lines.join("\n")
}

function buildIndexLines(leaf: AssembledLeaf, toolboxEntries: readonly ToolboxEntryContext[]): string[] {
    const rows = collectIndexRows(leaf, toolboxEntries)
    if (rows.length === 0) return []
    const width = Math.max(...rows.map(row => String(row.line).length))
    return [`// ${GENERATED_DIR}/${leaf.fileName}`, ...rows.map(row => `//   L${String(row.line).padEnd(width)}  ${row.label}`)]
}

function collectIndexRows(leaf: AssembledLeaf, toolboxEntries: readonly ToolboxEntryContext[]): IndexRow[] {
    const lines = leaf.code.split("\n")
    const rows: IndexRow[] = []
    const declarationLineByName = new Map<string, number>()
    lines.forEach((line, index) => {
        const declaration = line.match(DECLARATION_PATTERN)
        if (declaration?.[1]) declarationLineByName.set(declaration[3], index + 1)
    })

    const typeNameToToolboxKey = new Map(toolboxEntries.map(entry => [entry.typeName, entry.key]))
    let openBlock: { type: "tools"; key: string } | { type: "triggers"; key: string } | undefined

    lines.forEach((line, index) => {
        const lineNumber = index + 1

        if (openBlock) {
            if (line === "}") {
                openBlock = undefined
                return
            }
            const method = line.match(/^ {4}(\w+)[(<]/)
            if (!method) return
            if (openBlock.type === "tools") {
                const paramsType = line.match(/params: (\w+)/)?.[1]
                const paramsLine = paramsType ? declarationLineByName.get(paramsType) : undefined
                const paramsSuffix = paramsLine ? `  (params L${paramsLine})` : ""
                rows.push({ line: lineNumber, label: `toolbox.${openBlock.key}.${method[1]}()${paramsSuffix}` })
            } else {
                rows.push({ line: lineNumber, label: `Triggers.${openBlock.key}.${method[1]}()` })
            }
            return
        }

        const toolsBlock = line.match(/^export type (\w+) = \{$/)
        if (toolsBlock && typeNameToToolboxKey.has(toolsBlock[1])) {
            openBlock = { type: "tools", key: typeNameToToolboxKey.get(toolsBlock[1])! }
            return
        }
        const triggersBlock = line.match(/^export const (\w+)Triggers = \{$/)
        if (triggersBlock) {
            openBlock = { type: "triggers", key: triggersBlock[1] }
            return
        }

        const declaration = line.match(DECLARATION_PATTERN)
        if (!declaration || !declaration[1]) return
        const [, , keyword, name] = declaration
        if (keyword === "class") rows.push({ line: lineNumber, label: `class ${name}` })
        else if (keyword === "function") rows.push({ line: lineNumber, label: `function ${name}()` })
        else if ((keyword === "type" || keyword === "interface") && indexableTypeName(leaf.kind, name)) rows.push({ line: lineNumber, label: `type ${name}` })
    })
    return rows
}

function indexableTypeName(kind: LeafKind, name: string): boolean {
    switch (kind) {
        case "common":
            return true
        case "tools":
            return !/(Params|Result|GeneratedTools)$/.test(name)
        case "schemas":
            return /(RecordValues|InputValues|EntryValues|EntryRecordValues|ValuesFor|FilterFor)$/.test(name) || name === "GeneratedAttioObject" || name === "GeneratedAttioList"
        case "triggers":
            return false
        default:
            throw kind satisfies never
    }
}

function buildSdkImportLines(body: string, candidates: readonly string[], ownNames: ReadonlySet<string>): string[] {
    const used = candidates.filter(name => !ownNames.has(name) && referencesName(body, name))
    if (used.length === 0) return []
    if (used.length > 3) {
        return ["import {", ...used.map(name => `    ${name},`), '} from "terse-sdk"']
    }
    return [`import { ${used.join(", ")} } from "terse-sdk"`]
}

function buildSiblingImportLines(body: string, ownNames: ReadonlySet<string>, siblingDeclarations: readonly DeclaredName[], specifier: string): string[] {
    const used = siblingDeclarations.filter(declaration => declaration.exported && !ownNames.has(declaration.name) && referencesName(body, declaration.name))
    const values = used.filter(declaration => declaration.kind === "value").map(declaration => declaration.name)
    const types = used.filter(declaration => declaration.kind === "type").map(declaration => declaration.name)
    const lines: string[] = []
    if (values.length > 0) lines.push(`import { ${values.join(", ")} } from "${specifier}"`)
    if (types.length > 0) lines.push(`import type { ${types.join(", ")} } from "${specifier}"`)
    return lines
}

const DECLARATION_PATTERN = /^(export )?(?:declare )?(?:abstract )?(type|interface|class|function|const|enum)\s+(\w+)/

function extractDeclarations(body: string): DeclaredName[] {
    const declarations: DeclaredName[] = []
    const seen = new Set<string>()
    for (const line of body.split("\n")) {
        const match = line.match(DECLARATION_PATTERN)
        if (!match || seen.has(match[3])) continue
        seen.add(match[3])
        declarations.push({ name: match[3], kind: match[2] === "type" || match[2] === "interface" ? "type" : "value", exported: Boolean(match[1]) })
    }
    return declarations
}

function referencesName(body: string, name: string): boolean {
    return new RegExp(`\\b${name}\\b`).test(body)
}

function moduleName(fileName: string): string {
    return fileName.replace(/\.ts$/, "")
}

function postprocess(code: string): string {
    return code.replace(/\n{3,}/g, "\n\n").replace(/\n+$/, "")
}

const KIND_TIER: Record<LeafKind, number> = { common: 0, schemas: 1, tools: 2, triggers: 3 }

export interface AssembleGeneratedFilesInput {
    availableIntegrations?: string
    moduleOutputs: readonly ModuleOutput[]
    commonToolDeclarations: readonly string[]
}

interface AssembledLeaf extends LeafFile {
    code: string
    exports: DeclaredName[]
}

interface DeclaredName {
    name: string
    kind: "type" | "value"
    exported: boolean
}

interface IndexRow {
    line: number
    label: string
}
