import { IntegrationType } from "terse-types"
import ts from "typescript"

import type { GeneratedFile } from "../LanguageProvider.js"
import { readTemplateFile } from "../templateUtils.js"

import type { LeafFile, LeafKind, ModuleOutput, ToolboxEntryContext } from "./modules/IntegrationModule.js"
import { ModuleTemplateRenderer } from "./modules/templateRenderer.js"

const GENERATED_DIR = "terse.generated"

const LEAF_BANNER = [
    "// Auto-generated by `terse generate` — do not edit manually.",
    '// Part of the terse.generated bundle: import symbols from "./terse.generated" (the root file), which re-exports everything here.'
].join("\n")

export function assembleGeneratedFiles(input: AssembleGeneratedFilesInput): GeneratedFile[] {
    const renderer = ModuleTemplateRenderer.getInstance()
    const outputs = input.moduleOutputs.filter(output => output.leafFiles.length > 0)

    const imports = collectSdkImportCandidates(outputs)
    const leaves: LeafFile[] = [...buildCommonLeaf(renderer, input.commonToolDeclarations), ...outputs.flatMap(output => output.leafFiles)]
    const declarations = new Map(leaves.map(leaf => [leaf.fileName, extractDeclarations(leaf.body)]))
    const assembled = leaves.map(leaf => assembleLeaf(leaf, imports, leaves, declarations))

    const toolboxEntries = outputs.flatMap(output => output.toolboxEntries).sort((a, b) => a.key.localeCompare(b.key))
    const root = assembleRoot(renderer, input, outputs, imports, toolboxEntries, assembled)
    return [root, ...assembled.map(leaf => ({ fileName: `${GENERATED_DIR}/${leaf.fileName}`, code: leaf.code }))]
}

function collectSdkImportCandidates(outputs: readonly ModuleOutput[]): string[] {
    const candidates = new Set(outputs.flatMap(output => [...output.sdkImports]))
    const declaredNames = new Set(outputs.flatMap(output => [...output.triggerDeclaredNames]))
    declaredNames.forEach(name => candidates.delete(name))
    if (declaredNames.size > 0) candidates.add("SDKTrigger")
    outputs.flatMap(output => [...output.triggerExtraImports]).forEach(name => candidates.add(name))
    return [...candidates].sort()
}

function buildCommonLeaf(renderer: ModuleTemplateRenderer, commonToolDeclarations: readonly string[]): LeafFile[] {
    if (commonToolDeclarations.length === 0) return []
    return [{ fileName: "common.ts", kind: "common", body: renderer.renderCodegenTemplate("common.hbs", { commonToolDeclarations }) }]
}

function aggregateLines(outputs: readonly ModuleOutput[], linesOf: (output: ModuleOutput) => readonly string[]): string[] {
    const outputByType = new Map(outputs.map(output => [output.integration, output]))
    return Object.values(IntegrationType).flatMap(type => {
        const output = outputByType.get(type)
        return output ? [...linesOf(output)] : []
    })
}

function assembleLeaf(leaf: LeafFile, importCandidates: readonly string[], allLeaves: LeafFile[], declarations: Map<string, DeclaredName[]>): AssembledLeaf {
    const ownNames = new Set((declarations.get(leaf.fileName) ?? []).map(declaration => declaration.name))
    const referencedNames = collectReferencedNames(leaf.body)
    const sdkImportLines = buildSdkImportLines(referencedNames, importCandidates, ownNames)
    const siblingImportLines = allLeaves
        .filter(sibling => KIND_TIER[sibling.kind] < KIND_TIER[leaf.kind])
        .flatMap(sibling => buildSiblingImportLines(referencedNames, ownNames, declarations.get(sibling.fileName) ?? [], `./${moduleName(sibling.fileName)}.js`))
    const importBlock = [...sdkImportLines, ...siblingImportLines].join("\n")
    const code = postprocess([LEAF_BANNER, importBlock, leaf.body].filter(Boolean).join("\n\n"))
    return { ...leaf, code, exports: (declarations.get(leaf.fileName) ?? []).filter(declaration => declaration.exported) }
}

function assembleRoot(
    renderer: ModuleTemplateRenderer,
    input: AssembleGeneratedFilesInput,
    outputs: readonly ModuleOutput[],
    importCandidates: readonly string[],
    toolboxEntries: readonly ToolboxEntryContext[],
    leaves: AssembledLeaf[]
): GeneratedFile {
    const body = renderer.renderCodegenTemplate("root.hbs", {
        toolboxEntries,
        triggersAggregateLines: aggregateLines(outputs, output => output.triggersAggregateLines),
        skillsAggregateLines: aggregateLines(outputs, output => output.skillsAggregateLines)
    })
    const ownNames = new Set(extractDeclarations(body).map(declaration => declaration.name))
    const referencedNames = collectReferencedNames(body)
    const sdkImportLines = buildSdkImportLines(referencedNames, [...new Set([...importCandidates, "TerseAgent"])].sort(), ownNames)
    const siblingImportLines = leaves.flatMap(leaf => buildSiblingImportLines(referencedNames, ownNames, leaf.exports, `./${GENERATED_DIR}/${moduleName(leaf.fileName)}.js`))
    const reexportLines = leaves.map(leaf => `export * from "./${GENERATED_DIR}/${moduleName(leaf.fileName)}.js"`)
    const header = buildRootHeader(input.availableIntegrations, toolboxEntries, leaves)
    const code = postprocess([header, [...sdkImportLines, ...siblingImportLines].join("\n"), reexportLines.join("\n"), body].filter(Boolean).join("\n\n"))
    return { fileName: "terse.generated.ts", code }
}

function buildRootHeader(availableIntegrations: string | undefined, toolboxEntries: readonly ToolboxEntryContext[], leaves: AssembledLeaf[]): string {
    const lines: string[] = ["// Auto-generated by `terse generate` — do not edit manually.", "// Re-run `terse generate` to update."]
    if (availableIntegrations) {
        lines.push("//")
        lines.push(`// The integrations currently available in Terse: ${availableIntegrations}.`)
        lines.push("// Connect one with `terse integrate connect <type>`; list its tools with `terse integrate tool <type> --json`.")
    }
    lines.push("//")
    lines.push("// This file is the only import surface — everything generated is re-exported here:")
    lines.push('//   import { Triggers, Skills, toolbox, ... } from "./terse.generated"')
    lines.push("// The terse.generated/ folder holds the per-integration declarations. Read only the files you need:")
    lines.push("//   <integration>.triggers.ts — trigger factories (Triggers.<integration>.*) and their payload types")
    lines.push("//   <integration>.tools.ts    — typed tool methods (toolbox.<integration>.*), their Params/Result types, pinned resources, and skills")
    if (leaves.some(leaf => leaf.kind === "schemas")) {
        lines.push("//   <integration>.schemas.ts  — workspace-specific value/record types (Attio objects and lists)")
    }
    lines.push("//   terse.triggers.ts / terse.tools.ts — built-in triggers (schedule, webhook, webMonitor), built-in tools, and the web/imageEdit/memory skills")
    lines.push("// Below the index, this file only composes: the Triggers/Skills/toolbox aggregates re-export what the folder defines.")
    lines.push("")
    lines.push(readTemplateFile("typescript/codegen/sdk-primitives.hbs").trimEnd())

    const indexLines = leaves.flatMap(leaf => buildIndexLines(leaf, toolboxEntries))
    if (indexLines.length > 0) {
        lines.push("//")
        lines.push("// Index of the generated files. Line numbers are exact as of the last `terse generate`;")
        lines.push("// if a formatter has touched a file since, search for the symbol name instead.")
        lines.push("//")
        lines.push(...indexLines)
    }
    return lines.join("\n")
}

function buildIndexLines(leaf: AssembledLeaf, toolboxEntries: readonly ToolboxEntryContext[]): string[] {
    const rows = collectIndexRows(leaf, toolboxEntries)
    if (rows.length === 0) return []
    const width = Math.max(...rows.map(row => String(row.line).length))
    return [`// ${GENERATED_DIR}/${leaf.fileName}`, ...rows.map(row => `//   L${String(row.line).padEnd(width)}  ${row.label}`)]
}

function collectIndexRows(leaf: AssembledLeaf, toolboxEntries: readonly ToolboxEntryContext[]): IndexRow[] {
    const source = parseSource(leaf.code)
    const lineOf = (node: ts.Node): number => source.getLineAndCharacterOfPosition(node.getStart(source)).line + 1
    const typeNameToToolboxKey = new Map(toolboxEntries.map(entry => [entry.typeName, entry.key]))
    const declarationLineByName = new Map(
        topLevelDeclarations(source)
            .filter(declaration => declaration.exported)
            .map(declaration => [declaration.name, lineOf(declaration.statement)])
    )

    const rows: IndexRow[] = []
    for (const statement of source.statements) {
        if (!hasExportModifier(statement)) continue

        if (ts.isTypeAliasDeclaration(statement) && ts.isTypeLiteralNode(statement.type)) {
            const toolboxKey = typeNameToToolboxKey.get(statement.name.text)
            if (toolboxKey !== undefined) {
                rows.push(...toolboxMethodRows(statement.type, toolboxKey, declarationLineByName, lineOf))
                continue
            }
        }

        const triggersConst = matchTriggersConst(statement)
        if (triggersConst) {
            rows.push(...triggerMethodRows(triggersConst.initializer, triggersConst.key, lineOf))
            continue
        }

        if (ts.isClassDeclaration(statement) && statement.name) rows.push({ line: lineOf(statement), label: `class ${statement.name.text}` })
        else if (ts.isFunctionDeclaration(statement) && statement.name) rows.push({ line: lineOf(statement), label: `function ${statement.name.text}()` })
        else if ((ts.isTypeAliasDeclaration(statement) || ts.isInterfaceDeclaration(statement)) && indexableTypeName(leaf.kind, statement.name.text)) {
            rows.push({ line: lineOf(statement), label: `type ${statement.name.text}` })
        }
    }
    return rows
}

function toolboxMethodRows(type: ts.TypeLiteralNode, toolboxKey: string, declarationLineByName: ReadonlyMap<string, number>, lineOf: (node: ts.Node) => number): IndexRow[] {
    return type.members.flatMap(member => {
        if (!ts.isMethodSignature(member) || !ts.isIdentifier(member.name)) return []
        const firstParamType = member.parameters[0]?.type
        const paramsLine = firstParamType && ts.isTypeReferenceNode(firstParamType) && ts.isIdentifier(firstParamType.typeName) ? declarationLineByName.get(firstParamType.typeName.text) : undefined
        const paramsSuffix = paramsLine ? `  (params L${paramsLine})` : ""
        return [{ line: lineOf(member), label: `toolbox.${toolboxKey}.${member.name.text}()${paramsSuffix}` }]
    })
}

function triggerMethodRows(initializer: ts.ObjectLiteralExpression, triggersKey: string, lineOf: (node: ts.Node) => number): IndexRow[] {
    return initializer.properties.flatMap(property => {
        if (!ts.isMethodDeclaration(property) || !ts.isIdentifier(property.name)) return []
        return [{ line: lineOf(property), label: `Triggers.${triggersKey}.${property.name.text}()` }]
    })
}

function matchTriggersConst(statement: ts.Statement): { key: string; initializer: ts.ObjectLiteralExpression } | undefined {
    if (!ts.isVariableStatement(statement) || statement.declarationList.declarations.length !== 1) return undefined
    const [declaration] = statement.declarationList.declarations
    if (!ts.isIdentifier(declaration.name) || !declaration.name.text.endsWith("Triggers")) return undefined
    const key = declaration.name.text.slice(0, -"Triggers".length)
    if (key.length === 0 || !declaration.initializer || !ts.isObjectLiteralExpression(declaration.initializer)) return undefined
    return { key, initializer: declaration.initializer }
}

function indexableTypeName(kind: LeafKind, name: string): boolean {
    switch (kind) {
        case "common":
            return true
        case "tools":
            return !/(Params|Result|GeneratedTools)$/.test(name)
        case "schemas":
            return /(RecordValues|InputValues|EntryValues|EntryRecordValues|ValuesFor|FilterFor)$/.test(name) || name === "GeneratedAttioObject" || name === "GeneratedAttioList"
        case "triggers":
            return false
        default:
            throw kind satisfies never
    }
}

function buildSdkImportLines(referencedNames: ReadonlySet<string>, candidates: readonly string[], ownNames: ReadonlySet<string>): string[] {
    const used = candidates.filter(name => !ownNames.has(name) && referencedNames.has(name))
    if (used.length === 0) return []
    if (used.length > 3) {
        return ["import {", ...used.map(name => `    ${name},`), '} from "terse-sdk"']
    }
    return [`import { ${used.join(", ")} } from "terse-sdk"`]
}

function buildSiblingImportLines(referencedNames: ReadonlySet<string>, ownNames: ReadonlySet<string>, siblingDeclarations: readonly DeclaredName[], specifier: string): string[] {
    const used = siblingDeclarations.filter(declaration => declaration.exported && !ownNames.has(declaration.name) && referencedNames.has(declaration.name))
    const values = used.filter(declaration => declaration.kind === "value").map(declaration => declaration.name)
    const types = used.filter(declaration => declaration.kind === "type").map(declaration => declaration.name)
    const lines: string[] = []
    if (values.length > 0) lines.push(`import { ${values.join(", ")} } from "${specifier}"`)
    if (types.length > 0) lines.push(`import type { ${types.join(", ")} } from "${specifier}"`)
    return lines
}

function extractDeclarations(body: string): DeclaredName[] {
    const declarations: DeclaredName[] = []
    const seen = new Set<string>()
    for (const { name, kind, exported } of topLevelDeclarations(parseSource(body))) {
        if (seen.has(name)) continue
        seen.add(name)
        declarations.push({ name, kind, exported })
    }
    return declarations
}

function topLevelDeclarations(source: ts.SourceFile): TopLevelDeclaration[] {
    return source.statements.flatMap((statement): TopLevelDeclaration[] => {
        const exported = hasExportModifier(statement)
        if (ts.isTypeAliasDeclaration(statement) || ts.isInterfaceDeclaration(statement)) {
            return [{ statement, name: statement.name.text, kind: "type", exported }]
        }
        if (ts.isClassDeclaration(statement) || ts.isFunctionDeclaration(statement) || ts.isEnumDeclaration(statement)) {
            return statement.name ? [{ statement, name: statement.name.text, kind: "value", exported }] : []
        }
        if (ts.isVariableStatement(statement)) {
            return statement.declarationList.declarations.flatMap(declaration => (ts.isIdentifier(declaration.name) ? [{ statement, name: declaration.name.text, kind: "value", exported }] : []))
        }
        return []
    })
}

function collectReferencedNames(body: string): ReadonlySet<string> {
    const names = new Set<string>()
    const visit = (node: ts.Node): void => {
        if (ts.isIdentifier(node)) names.add(node.text)
        ts.forEachChild(node, visit)
    }
    visit(parseSource(body))
    return names
}

function hasExportModifier(statement: ts.Statement): boolean {
    return ts.canHaveModifiers(statement) && (ts.getModifiers(statement)?.some(modifier => modifier.kind === ts.SyntaxKind.ExportKeyword) ?? false)
}

function parseSource(text: string): ts.SourceFile {
    return ts.createSourceFile("generated.ts", text, ts.ScriptTarget.Latest, true)
}

function moduleName(fileName: string): string {
    return fileName.replace(/\.ts$/, "")
}

function postprocess(code: string): string {
    return code.replace(/\n{3,}/g, "\n\n").replace(/\n+$/, "")
}

const KIND_TIER: Record<LeafKind, number> = { common: 0, schemas: 1, tools: 2, triggers: 3 }

export interface AssembleGeneratedFilesInput {
    availableIntegrations?: string
    moduleOutputs: readonly ModuleOutput[]
    commonToolDeclarations: readonly string[]
}

interface AssembledLeaf extends LeafFile {
    code: string
    exports: DeclaredName[]
}

interface DeclaredName {
    name: string
    kind: "type" | "value"
    exported: boolean
}

interface TopLevelDeclaration extends DeclaredName {
    statement: ts.Statement
}

interface IndexRow {
    line: number
    label: string
}
