/**
 * Pure codegen function: GitHub integration data → TypeScript source text.
 * No I/O — all side effects live in generate.ts.
 */

import type { GithubIntegration } from "./shared/Integrations.js"

export interface GitHubRepo {
    id: number
    name: string
    owner: string
}

export interface GitHubInstanceData {
    integration: GithubIntegration
    repositories: GitHubRepo[]
}

// ── Helpers ──

function toPascalCase(s: string): string {
    return s
        .replace(/[^a-zA-Z0-9]+/g, " ")
        .trim()
        .split(/\s+/)
        .map(w => w.charAt(0).toUpperCase() + w.slice(1))
        .join("")
}

function generateGitHubInstance(inst: GitHubInstanceData, suffix: string): string {
    const repoClass = `Repository${suffix}`
    const triggerClass = `GithubTrigger${suffix}`
    const kbClass = `GithubKB${suffix}`
    const integrationId = inst.integration.id

    const lines: string[] = []

    // ── Repository class ──
    lines.push(`export class ${repoClass} {`)
    lines.push(`    constructor(public readonly repositoryId: number, public readonly name: string) {}`)
    lines.push("")
    const usedNames = new Set<string>()
    for (const repo of inst.repositories) {
        let staticName = toPascalCase(repo.name)
        while (usedNames.has(staticName)) {
            staticName += "_"
        }
        usedNames.add(staticName)
        lines.push(`    static ${staticName} = new ${repoClass}(${repo.id}, "${repo.name}")`)
    }
    lines.push(`}`)
    lines.push("")

    // ── GithubTrigger class (extends GitHubConfig) ──
    lines.push(`export class ${triggerClass} extends GitHubConfig {`)
    lines.push(`    constructor(repositories: ${repoClass}[]) {`)
    lines.push(`        super("${integrationId}", repositories.map(r => r.repositoryId))`)
    lines.push(`    }`)
    lines.push(`}`)
    lines.push("")

    // ── GithubKB class (extends GitHubKBConfig) ──
    lines.push(`export class ${kbClass} extends GitHubKBConfig {`)
    lines.push(`    constructor(repositories: ${repoClass}[]) {`)
    lines.push(`        super(`)
    lines.push(`            "${integrationId}",`)
    lines.push(`            repositories.map(r => r.repositoryId),`)
    lines.push(`            repositories.map(r => r.name)`)
    lines.push(`        )`)
    lines.push(`    }`)
    lines.push(`}`)
    lines.push("")

    return lines.join("\n")
}

// ── Main codegen entry point ──

export function generateCode(instances: GitHubInstanceData[]): string {
    if (instances.length === 0) {
        return [
            "// Auto-generated by `terse generate` — do not edit manually",
            "// No GitHub integrations found. Connect GitHub in the Terse dashboard,",
            "// then re-run `terse generate` to populate this file.",
            "",
        ].join("\n")
    }

    const needsSuffix = instances.length > 1
    const sections: string[] = []

    for (let i = 0; i < instances.length; i++) {
        const inst = instances[i]
        const suffix = needsSuffix
            ? toPascalCase(inst.integration.account_name || `Instance${i + 1}`)
            : ""
        sections.push(generateGitHubInstance(inst, suffix))
    }

    const header = [
        "// Auto-generated by `terse generate` — do not edit manually",
        "// Re-run `terse generate` to update.",
        "",
        "import { GitHubConfig, GitHubKBConfig } from \"terse-sdk\"",
        "",
    ]

    return [...header, ...sections].join("\n")
}
