export enum PosthogEvents {
    USER_SIGNED_UP = 'user_signed_up',
    USER_SIGNED_IN = 'user_signed_in',
    USER_SIGNED_OUT = 'user_signed_out',
    USER_INTEGRATED_GITHUB = 'user_integrated_github',
    USER_INTEGRATED_GMAIL = 'user_integrated_gmail',
    USER_INTEGRATED_SLACK = 'user_integrated_slack',
    USER_INTEGRATED_LINEAR = 'user_integrated_linear',
    USER_INTEGRATED_JIRA = 'user_integrated_jira',
    USER_INTEGRATED_NOTION = 'user_integrated_notion',
    USER_DISCONNECTED_LINEAR = 'user_disconnected_linear',
    USER_DISCONNECTED_JIRA = 'user_disconnected_slack',
    USER_DISCONNECTED_GITHUB = 'user_disconnected_github',
    USER_DISCONNECTED_GMAIL = 'user_disconnected_gmail',
    USER_DISCONNECTED_NOTION = 'user_disconnected_notion',
    LANDING_PAGE_VIEWED = 'landing_page_viewed',
    LANDING_PAGE_CTA_CLICKED = 'landing_page_cta_clicked',
    LANDING_PAGE_SCROLL_TO_FEATURES = 'landing_page_scroll_to_features',
}