# Terse SDK — Claude Code Skills

## About Terse

Terse is an automation platform where developers build background AI agents in TypeScript. Each agent reacts to events from integrated services (GitHub, Slack, Linear, etc.) and takes actions using an AI-powered agent runner with access to those same services as tools.

## Project Structure

```
my-project/
├── src/
│   ├── index.ts              # Job definitions — the entry point
│   └── terse.generated.ts    # Auto-generated types for connected integrations
├── package.json
├── tsconfig.json
├── .env                      # TERSE_API_KEY (required)
└── CLAUDE.md                 # This file
```

- `src/index.ts` is the only file you edit. It registers one or more jobs via `client.createJob()`.
- `src/terse.generated.ts` is generated by `terse generate`. It exports typed trigger factories, skill factories, and resource constants (repos, channels, teams, etc.) for each connected integration. **Never hand-edit this file.**
- `.env` must contain `TERSE_API_KEY`. Get one at the Terse dashboard under Profile → API Tokens.

## How Jobs Work

A job is a TypeScript object registered with `Terse.createJob()`. When a matching event arrives, Terse calls your `onTrigger` handler.

```typescript
import { Terse, TerseAgent, GithubPRInputEvent } from "terse-sdk"
import { GitHub, Slack, Repos, SlackChannel } from "./terse.generated"

const client = new Terse()

await client.createJob({
    name: "Summarize PR",
    triggers: [GitHub.onPROpened({ repo: Repos.MyOrg.MyRepo })],
    skills: [
        GitHub.skill({ repos: [Repos.MyOrg.MyRepo] }),
        Slack.skill({ channel: SlackChannel.General }),
    ],
    filter: async (event: GithubPRInputEvent) => {
        return event.sender.login !== "dependabot[bot]"
    },
    onTrigger: async (event: GithubPRInputEvent, Agent: TerseAgent) => {
        await Agent.runAndWait(
            `Summarize this PR: ${event.formatForAgentRunner()}. Post the summary to Slack.`
        )
    },
})
```

### CreateJobParameters

| Field | Type | Required | Description |
|-------|------|----------|-------------|
| `name` | `string` | Yes | Unique human-readable name for the job |
| `triggers` | `TypedTrigger[]` | Yes | One or more trigger configs defining when the job fires |
| `skills` | `ConfigInstance[]` | Yes | Integration configs giving the agent access to external tools |
| `filter` | `(event) => boolean \| Promise<boolean>` | No | Return `false` to skip the event without running the agent |
| `onTrigger` | `(event, Agent) => Promise<void>` | Yes | The automation logic |
| `webhookURL` | `string` | No | Optional webhook to call when the job runs |

### Multiple Jobs

A single project can register multiple jobs. Each `createJob()` call adds a job to the global registry.

```typescript
const client = new Terse()

await client.createJob({ name: "Job A", triggers: [...], skills: [...], onTrigger: async (event, Agent) => { ... } })
await client.createJob({ name: "Job B", triggers: [...], skills: [...], onTrigger: async (event, Agent) => { ... } })
```

## Terse CLI

| Command | Description |
|---------|-------------|
| `terse init [project-name]` | Scaffold a new Terse project with boilerplate code |
| `terse generate` | Fetch connected integrations and regenerate `terse.generated.ts` |
| `terse integrate` | Open the Terse web UI to connect new services |
| `terse run [job-name] --event <json>` | Run a job locally with a serialized event JSON |
| `terse run [job-name] --event-file <path>` | Run a job locally with event JSON from a file |
| `terse test [job-name]` | Fetch real sample events from your integrations and run interactively |
| `terse deploy` | Deploy all jobs to Terse (syncs with server — removed jobs are deleted remotely) |

### Typical Workflow

```bash
terse init my-project && cd my-project
terse integrate          # connect GitHub, Slack, etc. in the web UI
terse generate           # pull down typed integration constants
# edit src/index.ts
terse test               # pick a real event and run locally
terse deploy             # ship it
```

## Triggers

Triggers define what events fire a job. They come from `terse.generated.ts` after running `terse generate`.

### GitHub
```typescript
GitHub.onPROpened({ repo: Repos.MyOrg.MyRepo })
GitHub.onPRMerged({ repo: Repos.MyOrg.MyRepo })
GitHub.onPush({ repo: Repos.MyOrg.MyRepo })
GitHub.onIssueOpened({ repo: Repos.MyOrg.MyRepo })
```

### Slack
```typescript
Slack.onMessage({ channel: SlackChannel.General })
```

### Linear
```typescript
Linear.onIssueCreated({ team: LinearTeam.Engineering })
Linear.onIssueUpdated({ team: LinearTeam.Engineering })
```

### Jira
```typescript
Jira.onIssueCreated({ project: JiraProject.MyProject })
Jira.onIssueUpdated({ project: JiraProject.MyProject })
```

### Gmail
```typescript
Gmail.onNewEmail()
```

### Figma
```typescript
Figma.onComment()
```

### WorkOS
```typescript
WorkOS.onUserCreated()
WorkOS.onMembershipCreated()
WorkOS.onInvitationAccepted()
WorkOS.onOrganizationCreated()
```

### Cron / Schedule
```typescript
Schedule.every("0 9 * * 1")    // every Monday at 9 AM
Schedule.every("*/30 * * * *") // every 30 minutes
```

## Skills

Skills give the agent tools to act on external systems. The agent can **only** interact with systems it has skill configs for.

```typescript
skills: [
    GitHub.skill({ repos: [Repos.MyOrg.MyRepo, Repos.MyOrg.OtherRepo] }),
    Slack.skill({ channel: SlackChannel.General }),
    Linear.skill({ team: LinearTeam.Engineering }),
    Notion.skill({ database: NotionDB.Tasks }),
    Jira.skill({ project: JiraProject.MyProject }),
    Confluence.skill({ page: ConfluencePage.TeamDocs }),
    Gmail.skill(),
    PostHog.skill({ project: PostHogProject.Main }),
    Datadog.skill({ index: DatadogIndex.Main }),
    LaunchDarkly.skill({ project: LDProject.Default }),
    Attio.skill(),
    Snowflake.skill(),
    Terse.skill(),  // web search
]
```

## TerseAgent API

The agent is passed as the second argument to `onTrigger`.

### `Agent.runAndWait(prompt, event?)`

Runs the agent to completion. Use this for most jobs — it sends the prompt to the AI agent runner, which decides which tools to call and executes them.

```typescript
onTrigger: async (event, Agent) => {
    await Agent.runAndWait(`Summarize this PR: ${event.formatForAgentRunner()}`)
}
```

### `Agent.run(prompt, event?)`

Returns an `AsyncGenerator<TerseAgentResult>` for streaming output. Use when you need intermediate results.

```typescript
onTrigger: async (event, Agent) => {
    for await (const result of Agent.run("Analyze this event")) {
        if (result.type === "tool_call_completed") {
            console.log("Tool completed:", result.toolCallCompleted)
        }
    }
}
```

### `Agent.executeTool(toolName, params)`

Directly call a specific tool by name, bypassing the AI. Use for deterministic actions where you know exactly what tool and params to use.

```typescript
const result = await Agent.executeTool("slack_send_message", {
    channelId: "C12345",
    message: "Hello from Terse!"
})
```

### `Agent.tools.<integration>.<method>(params)`

Type-safe direct tool calls generated from your connected integrations. Available after `terse generate`.

```typescript
const message = await Agent.tools.slack.sendMessage({
    channelId: SlackChannel.General.channelId,
    message: "New PR opened!",
    thread_ts: "",
    blocks: ""
})
```

### When to Use What

| Approach | Use When |
|----------|----------|
| `Agent.runAndWait(prompt)` | The agent needs to decide what to do — summarize, analyze, choose actions |
| `Agent.tools.*` / `Agent.executeTool()` | You know exactly what tool call to make — send a specific message, create a specific issue |
| Combination | Do a deterministic action first (send message), then let the agent decide (reply in thread with analysis) |

## Event Types and Type Guards

### GitHub Events

```typescript
import { GithubPRInputEvent, GithubPushInputEvent, isGithubPREvent, isGithubPushEvent } from "terse-sdk"

// GithubPRInputEvent fields:
event.pullRequest.number    // PR number
event.pullRequest.title     // PR title
event.pullRequest.body      // PR description
event.pullRequest.state     // "open" | "closed"
event.pullRequest.merged    // boolean
event.pullRequest.head.ref  // source branch
event.pullRequest.base.ref  // target branch
event.pullRequest.author    // { login, email? }
event.pullRequest.url       // PR URL
event.sender                // { login, email? }
event.repository            // { id, name, owner, defaultBranch }
event.commits               // [{ sha, message, fileDiffs: [{ filename, diff }] }]

// GithubPushInputEvent fields:
event.branch                // branch that was pushed to
event.sender                // { login, email? }
event.repository            // { id, name, owner, defaultBranch }
event.commits               // [{ sha, message, fileDiffs: [{ filename, diff }] }]
```

### WorkOS Events

```typescript
import { WorkOSUserInputEvent, WorkOSMembershipInputEvent, isWorkOSUserEvent } from "terse-sdk"

// WorkOSUserInputEvent
event.user.id
event.user.email
event.user.firstName
event.user.lastName

// WorkOSMembershipInputEvent
event.membership.userId
event.membership.organizationId
event.membership.role.slug
event.membership.status

// WorkOSInvitationInputEvent
event.invitation.email
event.invitation.organizationId
event.invitation.state
```

### Using Type Guards

```typescript
import { isGithubPREvent, isGithubPushEvent } from "terse-sdk"

onTrigger: async (event, Agent) => {
    if (isGithubPREvent(event)) {
        // event is now typed as GithubPRInputEvent
        console.log(event.pullRequest.title)
    }
}
```

### Generic Event Interface

All events implement `InputEvent`:

```typescript
event.integrationType       // IntegrationType enum value
event.eventType             // specific event type string
event.formatForAgentRunner() // formatted string for agent prompts — include this in your prompt
event.debugLog()            // debug info string
```

## Serialized Event Format

When using `terse run --event`, provide JSON matching `SerializedEvent`:

```json
{
    "integrationType": "github",
    "eventType": "pull_request.opened",
    "formattedContent": "PR #42 opened by alice: Fix login bug",
    "debugLog": "pull_request.opened on MyOrg/MyRepo",
    "metadata": {
        "repository": { "id": 1, "name": "MyRepo", "owner": "MyOrg", "defaultBranch": "main" },
        "sender": { "login": "alice" },
        "pullRequest": { "number": 42, "title": "Fix login bug", "state": "open", "merged": false, "head": { "ref": "fix-login", "sha": "abc123" }, "base": { "ref": "main", "sha": "def456" }, "author": { "login": "alice" }, "url": "https://github.com/MyOrg/MyRepo/pull/42" }
    }
}
```

The `metadata` field enables the SDK to construct typed event classes (e.g., `GithubPRInputEvent`) instead of generic `SerializedEventInputEvent`.

## /create

Create a new Terse job. When the user asks you to create a job, follow these steps:

1. **Check `src/terse.generated.ts`** to see which integrations, repos, channels, teams, and other resources are available. If the file doesn't exist, tell the user to run `terse generate` first.

2. **Open `src/index.ts`** and add a new `client.createJob()` call. If the file already has jobs, add yours below the existing ones. If no `Terse` client exists yet, create one:
   ```typescript
   import { Terse, TerseAgent } from "terse-sdk"
   const client = new Terse()
   ```

3. **Pick triggers** based on what events the job should respond to. Import the trigger factories and resource constants from `./terse.generated`.

4. **Pick skills** for every integration the agent needs to interact with. The agent cannot use tools for services not listed in `skills`.

5. **Add a filter** if the job should skip certain events (bot users, draft PRs, specific labels, etc.).

6. **Write the `onTrigger` handler**:
   - Use `event.formatForAgentRunner()` in your prompt to give the agent context about the event.
   - For simple "do X then Y" flows, chain `Agent.tools.*` calls or `Agent.executeTool()`.
   - For AI decision-making (summarize, triage, analyze), use `Agent.runAndWait(prompt)`.
   - Combine both: do a deterministic tool call first, then pass its result into an agent run.

7. **Test** with `terse test` to verify with real sample events.

Example — create a job called "Label new issues":

```typescript
await client.createJob({
    name: "Label new issues",
    triggers: [GitHub.onIssueOpened({ repo: Repos.MyOrg.MyRepo })],
    skills: [GitHub.skill({ repos: [Repos.MyOrg.MyRepo] })],
    filter: async (event) => {
        return event.sender.login !== "dependabot[bot]"
    },
    onTrigger: async (event, Agent) => {
        await Agent.runAndWait(
            `Read this new GitHub issue and add appropriate labels (bug, feature, docs, question). ` +
            `Issue: ${event.formatForAgentRunner()}`
        )
    },
})
```

## /improve

Improve an existing Terse job. When the user asks you to improve a job, follow these steps:

1. **Find the job** by name in `src/index.ts`.

2. **Analyze** the current implementation for these improvement areas:

   **Prompt quality**
   - Is the prompt specific about what action to take?
   - Does it reference `event.formatForAgentRunner()` to include event context?
   - Does it tell the agent what to do on edge cases?
   - Is it too vague ("handle this") or too long (cramming multiple instructions)?

   **Event filtering**
   - Should bot-generated events be skipped? (e.g., `event.sender.login !== "dependabot[bot]"`)
   - Should draft PRs, WIP items, or specific labels be ignored?
   - Could a filter reduce unnecessary agent runs and save cost?

   **Type safety**
   - Is the event typed with the correct class (e.g., `GithubPRInputEvent` instead of generic `InputEvent`)?
   - Are type guards (`isGithubPREvent()`) used when handling events from multiple trigger types?
   - Are the trigger and skill types imported from `./terse.generated`?

   **Tool usage**
   - For deterministic actions (sending a known message, creating an issue with fixed fields), use `Agent.tools.*` or `Agent.executeTool()` instead of a full agent run.
   - For AI-driven decisions, use `Agent.runAndWait()`.
   - Could a multi-step approach work better? (e.g., fetch data with a tool call, then pass it into an agent prompt)

   **Error handling**
   - Does the code handle cases where event data might be missing?
   - Are there try/catch blocks around critical tool calls?
   - Does the agent prompt explain what to do if a tool call fails?

   **Skill configuration**
   - Are all needed integrations listed in `skills`?
   - Are unnecessary skills included that could be removed?
   - Are the repos/channels/teams scoped correctly (not too broad, not too narrow)?

3. **Implement the improvements** directly in `src/index.ts`.

4. **Explain** what you changed and why.

Common improvement patterns:

```typescript
// BEFORE: No filter, runs on every PR including bots
onTrigger: async (event, Agent) => {
    await Agent.runAndWait(`Review this PR: ${event.formatForAgentRunner()}`)
}

// AFTER: Filter bots, use typed events, better prompt
filter: async (event: GithubPRInputEvent) => {
    return !event.sender.login.includes("[bot]") && !event.pullRequest.merged
},
onTrigger: async (event: GithubPRInputEvent, Agent: TerseAgent) => {
    const prUrl = event.pullRequest.url
    const title = event.pullRequest.title

    await Agent.runAndWait(
        `Review PR "${title}" (${prUrl}). ` +
        `Look at the diff and leave a concise review comment. ` +
        `Focus on: correctness, edge cases, and naming. ` +
        `Skip style nits. If the PR looks good, approve it with a short note. ` +
        `Context: ${event.formatForAgentRunner()}`
    )
}
```

```typescript
// BEFORE: Agent decides everything
onTrigger: async (event, Agent) => {
    await Agent.runAndWait(`Send a welcome message to Slack about this PR: ${event.formatForAgentRunner()}`)
}

// AFTER: Deterministic message send, then agent analysis in thread
onTrigger: async (event: GithubPRInputEvent, Agent: TerseAgent) => {
    const message = await Agent.tools.slack.sendMessage({
        channelId: SlackChannel.Engineering.channelId,
        message: `New PR from ${event.sender.login}: ${event.pullRequest.title}`,
        thread_ts: "",
        blocks: "",
    })

    await Agent.runAndWait(
        `Summarize the changes in this PR and post as a thread reply ` +
        `(thread_ts: ${message.message_ts}). ` +
        `Context: ${event.formatForAgentRunner()}`
    )
}
```
