from __future__ import annotations

import re
import shutil
import subprocess
import sys
from pathlib import Path

HEADER_LINES = [
    "# AUTO-GENERATED - DO NOT EDIT. Run 'pnpm run generate:python-types' to regenerate.",
    "# ruff: noqa: E501",
]
REPO_ROOT = Path(__file__).resolve().parents[1]
GENERATED_FILE = REPO_ROOT / "packages/terse-python-sdk/src/terse_sdk/types/_generated.py"
CLASS_PATTERN = re.compile(r"^class (?P<name>[A-Za-z_][A-Za-z0-9_]*)\(", re.MULTILINE)
MODEL_SCHEMA_PATTERN = re.compile(
    r"^Model(?P<base>[A-Za-z_][A-Za-z0-9_]*?)Schema(?P<tail>[A-Z][A-Za-z0-9_]*)?$"
)
REDUNDANT_MODEL_CONFIG_PATTERN = re.compile(
    r"    model_config = ConfigDict\(\n(?:        .*\n)+?    \)\n"
)
CANONICAL_ENUM_BLOCKS = {
    "OutputItemType": "from terse_sdk.types.enums import ConfigType as OutputItemType",
    "RunHistoryActionIntegration": "from terse_sdk.types.enums import IntegrationType as RunHistoryActionIntegration",
    "RunHistoryActionType": "from terse_sdk.types.enums import RunHistoryActionType",
}
CANONICAL_ENUM_CLASS_PATTERN = r"^class {name}\(StrEnum\):\n(?:    .*\n)+\n"
GENERATED_ALIASES = {}
RESERVED_PUBLIC_NAMES = {
    "Agent",
    "ApprovalAction",
    "ApprovalRequest",
    "ChangedItem",
    "ConfigDetails",
    "ConfigInstance",
    "Error",
    "IntegrationDetails",
    "ModelEvent",
    "NotificationSettings",
    "OutputItem",
    "Role",
    "RunError",
    "RunHistoryDecision",
    "RunHistoryRecord",
    "RunHistoryTrigger",
    "SharedErrorContext",
    "TextDelta",
    "ToolCall",
    "User",
}
EXPLICIT_RENAMES = {
    # Schema class used inside NotionGetSchemaToolOutput (property definitions)
    "Schema": "NotionGetSchemaToolOutputPropertyDefinition",
    # NotionModifyBlocks discriminated union variants
    "NotionModifyBlocksToolOutputSchema1": "NotionModifyBlocksToolOutputAppendResult",
    "NotionModifyBlocksToolOutputSchema2": "NotionModifyBlocksToolOutputSingleBlockResult",
    "NotionModifyBlocksToolOutputSchema3": "NotionModifyBlocksToolOutputBatchResult",
    "NotionModifyBlocksToolOutputSchema4": "NotionModifyBlocksToolOutputFailure",
    # Operations within NotionModifyBlocks batch result
    "Operations": "NotionModifyBlocksToolOutputBatchAppendOperationResult",
    "Operations1": "NotionModifyBlocksToolOutputBatchUpdateOperationResult",
    "Operations2": "NotionModifyBlocksToolOutputBatchDeleteOperationResult",
    # NotionQueryDatabase discriminated union variants
    "NotionQueryDatabaseToolOutputSchema1": "NotionQueryDatabaseToolOutputSuccess",
    "NotionQueryDatabaseToolOutputSchema2": "NotionQueryDatabaseToolOutputFailure",
    # SearchPosthogEvents discriminated union variants
    "SearchPosthogEventsToolOutputSchema1": "SearchPosthogEventsToolOutputCountSummary",
    "SearchPosthogEventsToolOutputSchema2": "SearchPosthogEventsToolOutputEventList",
    "Event4": "SearchPosthogEventsToolOutputEvent",
    # SearchPosthogSessions discriminated union variants
    "SearchPosthogSessionsToolOutputSchema1": "SearchPosthogSessionsToolOutputPersonFound",
    "SearchPosthogSessionsToolOutputSchema2": "SearchPosthogSessionsToolOutputPersonNotFound",
}


def main() -> None:
    if not GENERATED_FILE.exists():
        raise FileNotFoundError(f"Generated file not found: {GENERATED_FILE}")

    content = GENERATED_FILE.read_text()
    validate_explicit_renames(content)
    rename_map = build_rename_map(content)

    for old_name, new_name in sorted(rename_map.items(), key=lambda item: len(item[0]), reverse=True):
        content = re.sub(rf"\b{re.escape(old_name)}\b", new_name, content)

    content = dedupe_canonical_enums(content)
    content = strip_redundant_model_config(content)
    content = append_generated_aliases(content)

    lines = content.splitlines()
    while lines and lines[0] in HEADER_LINES:
        lines.pop(0)
    while lines and not lines[0].strip():
        lines.pop(0)
    # Strip datamodel-codegen provenance comments (e.g. "# generated by datamodel-codegen:")
    lines = [line for line in lines if not re.match(r"^#\s*(generated by datamodel-codegen|filename:|timestamp:)", line)]
    while lines and not lines[0].strip():
        lines.pop(0)

    header = "\n".join(HEADER_LINES)
    body = "\n".join(lines)
    GENERATED_FILE.write_text(f"{header}\n\n{body}\n")

    run_ruff("check", "--fix", str(GENERATED_FILE))
    run_ruff("format", str(GENERATED_FILE))


def build_rename_map(content: str) -> dict[str, str]:
    rename_map: dict[str, str] = {}

    for match in CLASS_PATTERN.finditer(content):
        old_name = match.group("name")
        new_name = clean_name(old_name)
        if old_name == new_name:
            continue
        if new_name in RESERVED_PUBLIC_NAMES:
            continue
        rename_map[old_name] = new_name

    return rename_map


def validate_explicit_renames(content: str) -> None:
    missing = [old_name for old_name in EXPLICIT_RENAMES if f"class {old_name}(" not in content]
    if missing:
        missing_list = ", ".join(sorted(missing))
        print(f"[postprocess-generated-types] Warning: stale explicit rename keys: {missing_list}", file=sys.stderr)


def dedupe_canonical_enums(content: str) -> str:
    import_lines: list[str] = []

    for class_name, import_line in CANONICAL_ENUM_BLOCKS.items():
        content, removed = re.subn(
            CANONICAL_ENUM_CLASS_PATTERN.format(name=re.escape(class_name)),
            "",
            content,
            count=1,
            flags=re.MULTILINE,
        )
        if removed:
            import_lines.append(import_line)

    if not import_lines:
        return content

    marker = "from terse_sdk.types._base import TerseModel\n"
    canonical_import_block = "\n".join(import_lines)
    if canonical_import_block in content:
        return content
    if marker not in content:
        raise RuntimeError("Could not find TerseModel import while deduplicating canonical enums.")

    return content.replace(marker, f"{marker}{canonical_import_block}\n", 1)


def strip_redundant_model_config(content: str) -> str:
    return REDUNDANT_MODEL_CONFIG_PATTERN.sub("", content)


def append_generated_aliases(content: str) -> str:
    alias_lines = [f"{alias_name} = {target_name}" for alias_name, target_name in GENERATED_ALIASES.items()]
    alias_block = "\n".join(alias_lines)
    if alias_block in content:
        return content
    return f"{content.rstrip()}\n\n{alias_block}\n"


def clean_name(name: str) -> str:
    if explicit_name := EXPLICIT_RENAMES.get(name):
        return explicit_name

    match = MODEL_SCHEMA_PATTERN.match(name)
    if match is None:
        if name.endswith("Schema"):
            cleaned_name = name.removesuffix("Schema")
            if cleaned_name in RESERVED_PUBLIC_NAMES:
                return name
            return cleaned_name
        return name

    base = match.group("base")
    tail = match.group("tail") or ""
    normalized_tail = normalize_tail(base, tail)
    cleaned_name = f"{base}{normalized_tail}"

    if cleaned_name in RESERVED_PUBLIC_NAMES:
        return name.removeprefix("Model")

    return re.sub(r"(?<=[A-Za-z])(\d+)(?=[A-Z]|$)", r"Variant\1", cleaned_name)


def normalize_tail(base: str, tail: str) -> str:
    if not tail:
        return ""

    while tail.startswith(base):
        tail = tail.removeprefix(base)

    while tail.startswith("Schema"):
        tail = tail.removeprefix("Schema")

    while tail.startswith(base):
        tail = tail.removeprefix(base)

    if tail.startswith("Schema"):
        tail = tail.removeprefix("Schema")

    return tail


def run_ruff(*args: str) -> None:
    ruff = shutil.which("ruff")
    if ruff is not None:
        command = [ruff, *args]
    else:
        command = [sys.executable, "-m", "ruff", *args]

    subprocess.run(command, check=True, cwd=REPO_ROOT)


if __name__ == "__main__":
    main()
