"""
Generated by `terse generate`. Do not edit manually.

Type checking:
    uv run ty check src/
"""

from __future__ import annotations

from terse_sdk import (
    TriggerConfig,
    WebhookTrigger,
)


def _compact_dict(**values: object) -> dict[str, object]:
    """Drop None values while preserving falsey config values like False and []."""

    return {key: value for key, value in values.items() if value is not None}


# === Webhook ===


class Webhook:
    @staticmethod
    def on_request() -> TriggerConfig[WebhookTrigger]:
        return TriggerConfig(
            integration_id='system',
            integration_type='webhook',
            config_type='webhook_input',
            config={},
        )
