// Auto-generated by `terse generate` — do not edit manually
// Re-run `terse generate` to update.
import {
    CronTrigger,
    FrequencyUnit,
    ImageEditConfig,
    InferStructuredOutput,
    MemoryConfig,
    PosthogConfig,
    SlackAppMentionTrigger,
    SlackConfig,
    SlackEventType,
    SlackMessageTrigger,
    SlackOutputConfig,
    SlackReactionAddedTrigger,
    SlackTrigger,
    TerseAgent,
    TimeTriggerConfig,
    ToolInputByName,
    ToolOutputByName,
    TypedSkill,
    TypedTrigger,
    WebConfig,
    WebMonitorConfig,
    WebMonitorTrigger,
    WebhookInputConfig,
    WebhookTrigger
} from "terse-sdk"

// ── Slack ─────────────────────────────────────────────────────

export class SlackChannel {
    constructor(
        public readonly channelId: string,
        public readonly name: string
    ) {}

    static AllTerseInc = new SlackChannel("C09DEL0AUE5", "all-terse-inc")
    static MpdmOlivierTerse2Terse3Thomas1 = new SlackChannel("C0A2DV3N4GL", "mpdm-olivier--terse2--terse3--thomas-1")
}

export class SlackUser {
    constructor(
        public readonly userId: string,
        public readonly name: string
    ) {}

    static Slackbot = new SlackUser("USLACKBOT", "slackbot")
    static Thomas = new SlackUser("U09DEL0634Z", "thomas")
    static Olivier = new SlackUser("U09FXB1UPDM", "olivier")
}
// ── PostHog ───────────────────────────────────────────────────

export class PosthogProject {
    constructor(
        public readonly projectId: string,
        public readonly name: string
    ) {}

    static DefaultProject = new PosthogProject("220160", "Default project")
    static Terse = new PosthogProject("250907", "Terse")
    static TestBuggyApp = new PosthogProject("281984", "TestBuggyApp")
}

/**
 * Custom event names observed in your PostHog project over the last 180 days.
 * Built-in $-prefixed events (e.g. "$pageview") are always accepted alongside these.
 * Terse supports US PostHog Cloud (us.posthog.com) only; EU-hosted PostHog is not supported.
 */
export type PosthogEventName =
    | "action_taken"
    | "agent_triggered"
    | "job_triggered"
    | "job_completed"
    | "integration_added"
    | "agent_created"
    | "job_failed"
    | "project_deleted"
    | "project_created"
    | "project_deployed"
    | "user_signed_out"
    | "user_integrated_github"
    | "job_suspended"
    | "job_resumed"
    | "cli_logged_in"
    | "user_signed_in"
    | "job_created"
    | "job_auto_paused"
    | "job_disabled"
    | "project_deploy_failed"
    | "organization_created"
    | "job_enabled"
// ── Triggers ──────────────────────────────────────────────────

/**
 * Triggers available in your workspace.
 *
 * Type `Triggers.` in your editor to see every connected integration with triggers.
 * Use these in `createJob({ triggers: [...] })`.
 */
export const Triggers = {
    slack: {
        /** Trigger on any message in a channel */
        onMessage(opts: { channel: SlackChannel; userIds?: string[] }): TypedTrigger<SlackMessageTrigger> {
            return new SlackConfig("cmr3r2xb80002y5em42x4nqae", opts.channel.channelId, opts.channel.name, false, opts.userIds ?? [], [SlackEventType.MESSAGE])
        },
        /** Trigger on direct messages to the bot */
        onDm(opts?: { userIds?: string[] }): TypedTrigger<SlackMessageTrigger> {
            return new SlackConfig("cmr3r2xb80002y5em42x4nqae", undefined, undefined, true, opts?.userIds ?? [], [SlackEventType.MESSAGE])
        },
        /** Trigger when the Slack app is directly mentioned */
        onAppMention(opts: { channel: SlackChannel; userIds?: string[] }): TypedTrigger<SlackAppMentionTrigger> {
            return new SlackConfig("cmr3r2xb80002y5em42x4nqae", opts.channel.channelId, opts.channel.name, false, opts.userIds ?? [], [SlackEventType.APP_MENTION])
        },
        /** Trigger when a reaction is added to a message in a channel */
        onReactionAdded(opts: { channel: SlackChannel; userIds?: string[] }): TypedTrigger<SlackReactionAddedTrigger> {
            return new SlackConfig("cmr3r2xb80002y5em42x4nqae", opts.channel.channelId, opts.channel.name, false, opts.userIds ?? [], [SlackEventType.REACTION_ADDED])
        },
        /** Trigger on all Slack events (messages + DMs) for a channel */
        trigger(opts?: { channel?: SlackChannel; listenToUserDms?: boolean; userIds?: string[]; eventTypes?: SlackEventType[] }): TypedTrigger<SlackTrigger> {
            return new SlackConfig("cmr3r2xb80002y5em42x4nqae", opts?.channel?.channelId, opts?.channel?.name, opts?.listenToUserDms, opts?.userIds ?? [], opts?.eventTypes)
        }
    },
    schedule: {
        /** Run on a cron schedule */
        cron(opts: { expression: string }): TypedTrigger<CronTrigger> {
            return new TimeTriggerConfig(opts.expression)
        }
    },
    webhook: {
        /** Trigger via an external HTTP request to a generated URL */
        onRequest<TBody = unknown>(): TypedTrigger<WebhookTrigger<TBody>> {
            return new WebhookInputConfig()
        }
    },
    webMonitor: {
        /** Trigger when a query against the live web matches the given schema */
        onEvent<const TSchema>(opts: { query: string; frequency: { number: number; unit: FrequencyUnit }; outputSchema?: TSchema }): TypedTrigger<WebMonitorTrigger<InferStructuredOutput<TSchema>>> {
            return new WebMonitorConfig(opts.query, opts.frequency, opts.outputSchema)
        }
    }
}
// ── Skills ────────────────────────────────────────────────────

/**
 * Skills available in your workspace.
 *
 * Type `Skills.` in your editor to see every connected integration's skill at a glance.
 * Use these in `generateText({ skills: [...] })` (or `TerseAgent.create({ skills: [...] })`).
 */
export const Skills = {
    /** Slack — send messages and manage threads in a specific channel */
    slack(opts: { channel: SlackChannel; userIds?: string[]; userNames?: string[]; listenToUserDms?: boolean }): TypedSkill<"slack_send_message"> {
        return new SlackOutputConfig("cmr3r2xb80002y5em42x4nqae", opts.channel.channelId ?? null, opts.channel.name ?? null, opts.userIds ?? [], opts.userNames ?? null, opts.listenToUserDms)
    },
    /** PostHog — query analytics for a specific project */
    posthog(opts: { project: PosthogProject }): TypedSkill<never> {
        return new PosthogConfig("cmr9jgvgn0001y5uz1kcdoic0", opts.project.projectId, opts.project.name)
    },
    /** Web — built-in web search, page extraction, and multi-source research. Pass `allowedDomains` to restrict search and page extraction to specific sites (and their subdomains). */
    web(opts: { allowedDomains?: string[] } = {}): TypedSkill<"web_search" | "web_extract" | "web_research"> {
        return new WebConfig(opts)
    },
    /** ImageEdit — edit and generate images */
    imageEdit(): TypedSkill<"image_edit"> {
        return new ImageEditConfig()
    },
    /** Memory — built-in persistent memory the agent reads and writes under /memories, scoped to this job and surviving across runs. */
    memory(): TypedSkill<"memory"> {
        return new MemoryConfig()
    }
}
// ── Typed Tools ───────────────────────────────────────────────

/** Send message to a Slack channel or DM. Provide channelId (C…/G…/D…) or slackUserId (U…) to open or reuse a 1:1 DM. Supports plain text (mrkdwn) or Block Kit (JSON blocks). If both are set, channelId is used. */
export type SlackSendMessageParams = Omit<ToolInputByName["slack_send_message"], "integrationId">

/** List Slack workspace users (id and name). Use this to resolve user IDs to names when needed.
Returns non-bot members. Optionally filter by name with the query parameter. */
export type SlackListUsersParams = Omit<ToolInputByName["slack_list_users"], "integrationId">

/** List available Slack channels and conversations (public, private, DMs, multi-person DMs) that the integration can access.
Use this to discover channel IDs before reading conversation history.
Supports pagination: if the response includes nextCursor and hasMore, pass nextCursor as the cursor parameter on the next call to fetch more. */
export type SlackListChannelsParams = Omit<ToolInputByName["slack_list_channels"], "integrationId">

/** Read message history from a Slack channel or DM.
Use the channel ID from slack_list_channels. Supports public channels, private channels, and DMs.
Supports pagination: if the response includes nextCursor and hasMore, pass nextCursor as the cursor parameter on the next call to fetch more messages. */
export type SlackReadConversationParams = Omit<ToolInputByName["slack_read_conversation"], "integrationId">

/** Query PostHog logs with flexible filtering. Returns logs data and a link to view logs in PostHog. You can filter by user email, log severity levels (error, warn, info, debug), message text search, or combinations. At least one filter (user email, severity levels, or message search) should be provided to avoid overly broad queries. Use this when you need to investigate user activity, errors, or events in PostHog logs. */
export type SearchPosthogLogsParams = Omit<ToolInputByName["searchPosthogLogs"], "integrationId">

/** Query PostHog session recordings for a specific user by their email address. Returns session recordings data and links to view sessions in PostHog. Use this when you need to replay user sessions, investigate user behavior, or understand how users interact with the application. Returns the most recent session recordings first. */
export type SearchPosthogSessionsParams = Omit<ToolInputByName["searchPosthogSessions"], "integrationId">

/** Fetch and decode session replay events from PostHog. Returns summarized meaningful events (clicks, inputs, scroll, console logs, network errors, navigation) within a specified time window. Use this to investigate what a user did during a session - what they clicked, what they typed, any errors that occurred, etc. The events are decoded and summarized for easy analysis. */
export type GetPosthogSessionEventsParams = Omit<ToolInputByName["getPosthogSessionEvents"], "integrationId">

/** List PostHog event names with how often each occurred, most frequent first (US PostHog Cloud only). Scope with distinctId to profile a single user's activity, or with event/person propertyFilters and a date range. */
export type ListPosthogEventNamesParams = Omit<ToolInputByName["listPosthogEventNames"], "integrationId">

/** Fetch PostHog analytics events, newest first (US PostHog Cloud only). Filter by eventName, distinctId, and event/person propertyFilters. Use listPosthogEventNames first to discover which event names exist. */
export type SearchPosthogEventsParams = Omit<ToolInputByName["searchPosthogEvents"], "integrationId" | "eventName"> & { eventName?: PosthogEventName | `$${string}` | null }

/** Persistent memory stored under /memories that survives across runs. Commands: view (read a file or list a directory), create, str_replace, insert, delete, rename. Always view /memories before starting a task, and record durable progress and learnings as you work. */
export type MemoryParams = ToolInputByName["memory"]

/** Search the web for up-to-date information. Returns ranked results with titles, URLs, and content snippets. Use for questions about current events, facts, or topics requiring web sources. */
export type WebSearchParams = ToolInputByName["web_search"]

/** Extract the full text content from one or more web page URLs. Use this when you need to read the complete contents of a specific page. */
export type WebExtractParams = ToolInputByName["web_extract"]

/** Conduct deep, multi-source research on a topic. Autonomously searches across many sources and returns a comprehensive report with citations. Best for complex questions requiring synthesis across multiple sources. Takes longer than a regular search (up to 2 minutes). */
export type WebResearchParams = ToolInputByName["web_research"]

/** Edit or transform an image from a URL using a natural language prompt. Supports crops, style changes, object removal/addition, color adjustments, and other visual edits. The edited image is automatically sent to the chat UI for the user to see. */
export type ImageEditParams = ToolInputByName["image_edit"]

export type GeneratedTools = {
    posthog: {
        /** Query PostHog logs with flexible filtering. Returns logs data and a link to view logs in PostHog. You can filter by user email, log severity levels (error, warn, info, debug), message text search, or combinations. At least one filter (user email, severity levels, or message search) should be provided to avoid overly broad queries. Use this when you need to investigate user activity, errors, or events in PostHog logs. */
        searchLogs(params: SearchPosthogLogsParams): Promise<ToolOutputByName["searchPosthogLogs"]>
        /** Query PostHog session recordings for a specific user by their email address. Returns session recordings data and links to view sessions in PostHog. Use this when you need to replay user sessions, investigate user behavior, or understand how users interact with the application. Returns the most recent session recordings first. */
        searchSessions(params: SearchPosthogSessionsParams): Promise<ToolOutputByName["searchPosthogSessions"]>
        /** Fetch and decode session replay events from PostHog. Returns summarized meaningful events (clicks, inputs, scroll, console logs, network errors, navigation) within a specified time window. Use this to investigate what a user did during a session - what they clicked, what they typed, any errors that occurred, etc. The events are decoded and summarized for easy analysis. */
        getSessionEvents(params: GetPosthogSessionEventsParams): Promise<ToolOutputByName["getPosthogSessionEvents"]>
        /** List PostHog event names with how often each occurred, most frequent first (US PostHog Cloud only). Scope with distinctId to profile a single user's activity, or with event/person propertyFilters and a date range. */
        listEventNames(params: ListPosthogEventNamesParams): Promise<ToolOutputByName["listPosthogEventNames"]>
        /** Fetch PostHog analytics events, newest first (US PostHog Cloud only). Filter by eventName, distinctId, and event/person propertyFilters. Use listPosthogEventNames first to discover which event names exist. */
        searchEvents(params: SearchPosthogEventsParams): Promise<ToolOutputByName["searchPosthogEvents"]>
    }
    slack: {
        /** Send message to a Slack channel or DM. Provide channelId (C…/G…/D…) or slackUserId (U…) to open or reuse a 1:1 DM. Supports plain text (mrkdwn) or Block Kit (JSON blocks). If both are set, channelId is used. */
        sendMessage(params: SlackSendMessageParams): Promise<ToolOutputByName["slack_send_message"]>
        /** List Slack workspace users (id and name). Use this to resolve user IDs to names when needed.
Returns non-bot members. Optionally filter by name with the query parameter. */
        listUsers(params: SlackListUsersParams): Promise<ToolOutputByName["slack_list_users"]>
        /** List available Slack channels and conversations (public, private, DMs, multi-person DMs) that the integration can access.
Use this to discover channel IDs before reading conversation history.
Supports pagination: if the response includes nextCursor and hasMore, pass nextCursor as the cursor parameter on the next call to fetch more. */
        listChannels(params: SlackListChannelsParams): Promise<ToolOutputByName["slack_list_channels"]>
        /** Read message history from a Slack channel or DM.
Use the channel ID from slack_list_channels. Supports public channels, private channels, and DMs.
Supports pagination: if the response includes nextCursor and hasMore, pass nextCursor as the cursor parameter on the next call to fetch more messages. */
        readConversation(params: SlackReadConversationParams): Promise<ToolOutputByName["slack_read_conversation"]>
    }
    terse: {
        /** Persistent memory stored under /memories that survives across runs. Commands: view (read a file or list a directory), create, str_replace, insert, delete, rename. Always view /memories before starting a task, and record durable progress and learnings as you work. */
        memory(params: MemoryParams): Promise<ToolOutputByName["memory"]>
        /** Search the web for up-to-date information. Returns ranked results with titles, URLs, and content snippets. Use for questions about current events, facts, or topics requiring web sources. */
        webSearch(params: WebSearchParams): Promise<ToolOutputByName["web_search"]>
        /** Extract the full text content from one or more web page URLs. Use this when you need to read the complete contents of a specific page. */
        extractPage(params: WebExtractParams): Promise<ToolOutputByName["web_extract"]>
        /** Conduct deep, multi-source research on a topic. Autonomously searches across many sources and returns a comprehensive report with citations. Best for complex questions requiring synthesis across multiple sources. Takes longer than a regular search (up to 2 minutes). */
        research(params: WebResearchParams): Promise<ToolOutputByName["web_research"]>
        /** Edit or transform an image from a URL using a natural language prompt. Supports crops, style changes, object removal/addition, color adjustments, and other visual edits. The edited image is automatically sent to the chat UI for the user to see. */
        editImage(params: ImageEditParams): Promise<ToolOutputByName["image_edit"]>
    }
}

declare module "terse-sdk" {
    interface TerseAgent {
        readonly tools: GeneratedTools
    }
}

function createTools(agent: TerseAgent): GeneratedTools {
    const allowed: Set<string> = new Set(agent.skills.map(config => config.integrationType))
    return {
        ...(allowed.has("posthog")
            ? {
                  posthog: {
                      searchLogs: (params: SearchPosthogLogsParams) =>
                          TerseAgent.executeTool<ToolOutputByName["searchPosthogLogs"]>("searchPosthogLogs", { ...params, integrationId: "cmr9jgvgn0001y5uz1kcdoic0" }),
                      searchSessions: (params: SearchPosthogSessionsParams) =>
                          TerseAgent.executeTool<ToolOutputByName["searchPosthogSessions"]>("searchPosthogSessions", { ...params, integrationId: "cmr9jgvgn0001y5uz1kcdoic0" }),
                      getSessionEvents: (params: GetPosthogSessionEventsParams) =>
                          TerseAgent.executeTool<ToolOutputByName["getPosthogSessionEvents"]>("getPosthogSessionEvents", { ...params, integrationId: "cmr9jgvgn0001y5uz1kcdoic0" }),
                      listEventNames: (params: ListPosthogEventNamesParams) =>
                          TerseAgent.executeTool<ToolOutputByName["listPosthogEventNames"]>("listPosthogEventNames", { ...params, integrationId: "cmr9jgvgn0001y5uz1kcdoic0" }),
                      searchEvents: (params: SearchPosthogEventsParams) =>
                          TerseAgent.executeTool<ToolOutputByName["searchPosthogEvents"]>("searchPosthogEvents", { ...params, integrationId: "cmr9jgvgn0001y5uz1kcdoic0" })
                  }
              }
            : {}),
        ...(allowed.has("slack")
            ? {
                  slack: {
                      sendMessage: (params: SlackSendMessageParams) =>
                          TerseAgent.executeTool<ToolOutputByName["slack_send_message"]>("slack_send_message", { ...params, integrationId: "cmr3r2xb80002y5em42x4nqae" }),
                      listUsers: (params: SlackListUsersParams) =>
                          TerseAgent.executeTool<ToolOutputByName["slack_list_users"]>("slack_list_users", { ...params, integrationId: "cmr3r2xb80002y5em42x4nqae" }),
                      listChannels: (params: SlackListChannelsParams) =>
                          TerseAgent.executeTool<ToolOutputByName["slack_list_channels"]>("slack_list_channels", { ...params, integrationId: "cmr3r2xb80002y5em42x4nqae" }),
                      readConversation: (params: SlackReadConversationParams) =>
                          TerseAgent.executeTool<ToolOutputByName["slack_read_conversation"]>("slack_read_conversation", { ...params, integrationId: "cmr3r2xb80002y5em42x4nqae" })
                  }
              }
            : {}),
        ...(allowed.has("terse")
            ? {
                  terse: {
                      memory: (params: MemoryParams) => TerseAgent.executeTool<ToolOutputByName["memory"]>("memory", params),
                      webSearch: (params: WebSearchParams) => TerseAgent.executeTool<ToolOutputByName["web_search"]>("web_search", params),
                      extractPage: (params: WebExtractParams) => TerseAgent.executeTool<ToolOutputByName["web_extract"]>("web_extract", params),
                      research: (params: WebResearchParams) => TerseAgent.executeTool<ToolOutputByName["web_research"]>("web_research", params),
                      editImage: (params: ImageEditParams) => TerseAgent.executeTool<ToolOutputByName["image_edit"]>("image_edit", params)
                  }
              }
            : {})
    } as GeneratedTools
}

;(globalThis as any).__terse_createTools = createTools

/**
 * Deterministic tool calls without an agent.
 *
 * `toolbox` exposes every connected integration tool as a typed function. Unlike
 * `agent.tools`, it does not require constructing a `TerseAgent` and is not
 * filtered by `skills`. Use it when you know exactly which tool to call and
 * don't need an LLM in the loop.
 *
 * @example
 * ```ts
 * import { toolbox } from "./terse.generated"
 * await toolbox.slack.sendMessage({ channelId: "...", message: "hi" })
 * ```
 */
export const toolbox: GeneratedTools = {
    posthog: {
        searchLogs: (params: SearchPosthogLogsParams) => TerseAgent.executeTool<ToolOutputByName["searchPosthogLogs"]>("searchPosthogLogs", { ...params, integrationId: "cmr9jgvgn0001y5uz1kcdoic0" }),
        searchSessions: (params: SearchPosthogSessionsParams) =>
            TerseAgent.executeTool<ToolOutputByName["searchPosthogSessions"]>("searchPosthogSessions", { ...params, integrationId: "cmr9jgvgn0001y5uz1kcdoic0" }),
        getSessionEvents: (params: GetPosthogSessionEventsParams) =>
            TerseAgent.executeTool<ToolOutputByName["getPosthogSessionEvents"]>("getPosthogSessionEvents", { ...params, integrationId: "cmr9jgvgn0001y5uz1kcdoic0" }),
        listEventNames: (params: ListPosthogEventNamesParams) =>
            TerseAgent.executeTool<ToolOutputByName["listPosthogEventNames"]>("listPosthogEventNames", { ...params, integrationId: "cmr9jgvgn0001y5uz1kcdoic0" }),
        searchEvents: (params: SearchPosthogEventsParams) =>
            TerseAgent.executeTool<ToolOutputByName["searchPosthogEvents"]>("searchPosthogEvents", { ...params, integrationId: "cmr9jgvgn0001y5uz1kcdoic0" })
    },
    slack: {
        sendMessage: (params: SlackSendMessageParams) =>
            TerseAgent.executeTool<ToolOutputByName["slack_send_message"]>("slack_send_message", { ...params, integrationId: "cmr3r2xb80002y5em42x4nqae" }),
        listUsers: (params: SlackListUsersParams) => TerseAgent.executeTool<ToolOutputByName["slack_list_users"]>("slack_list_users", { ...params, integrationId: "cmr3r2xb80002y5em42x4nqae" }),
        listChannels: (params: SlackListChannelsParams) =>
            TerseAgent.executeTool<ToolOutputByName["slack_list_channels"]>("slack_list_channels", { ...params, integrationId: "cmr3r2xb80002y5em42x4nqae" }),
        readConversation: (params: SlackReadConversationParams) =>
            TerseAgent.executeTool<ToolOutputByName["slack_read_conversation"]>("slack_read_conversation", { ...params, integrationId: "cmr3r2xb80002y5em42x4nqae" })
    },
    terse: {
        memory: (params: MemoryParams) => TerseAgent.executeTool<ToolOutputByName["memory"]>("memory", params),
        webSearch: (params: WebSearchParams) => TerseAgent.executeTool<ToolOutputByName["web_search"]>("web_search", params),
        extractPage: (params: WebExtractParams) => TerseAgent.executeTool<ToolOutputByName["web_extract"]>("web_extract", params),
        research: (params: WebResearchParams) => TerseAgent.executeTool<ToolOutputByName["web_research"]>("web_research", params),
        editImage: (params: ImageEditParams) => TerseAgent.executeTool<ToolOutputByName["image_edit"]>("image_edit", params)
    }
}
